In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.shape

(284807, 31)

In [4]:
df = df.sample(100000)

In [5]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,94785.180840,0.010765,-0.000555,0.003074,0.002859,-0.003572,-0.001748,0.003606,-0.005425,-0.004414,...,-0.002197,0.001338,0.000810,-0.000101,-0.000501,0.001685,0.000025,-0.001380,88.498608,0.001820
std,47504.740268,1.936562,1.638865,1.499236,1.421274,1.344876,1.321446,1.216264,1.188016,1.102555,...,0.722294,0.725126,0.631122,0.606721,0.521914,0.483229,0.396549,0.314581,252.394599,0.042623
min,9.000000,-46.855047,-60.464618,-32.454198,-5.683171,-32.092129,-20.869626,-43.557242,-50.688419,-13.320155,...,-22.889347,-9.499423,-44.807735,-2.822684,-10.295397,-2.604551,-9.895244,-8.478686,0.000000,0.000000
25%,54198.750000,-0.915937,-0.597667,-0.884900,-0.854848,-0.691683,-0.769777,-0.554160,-0.210618,-0.644427,...,-0.226693,-0.538039,-0.161975,-0.356229,-0.317036,-0.325974,-0.070974,-0.052804,5.700000,0.000000
50%,84598.000000,0.027135,0.065952,0.180371,-0.019680,-0.057442,-0.277413,0.042578,0.020246,-0.055285,...,-0.029218,0.005559,-0.012005,0.040086,0.015337,-0.050627,0.001136,0.011064,22.000000,0.000000
75%,139341.750000,1.318048,0.801693,1.025749,0.746791,0.610432,0.394249,0.573452,0.323211,0.590798,...,0.185189,0.529976,0.147025,0.438380,0.351153,0.240714,0.090013,0.077707,77.150000,0.000000
max,172788.000000,2.451888,22.057729,4.040465,16.875344,29.016124,21.393069,34.303177,19.587773,10.392889,...,27.202839,8.316275,22.083545,3.998294,6.070850,3.463246,9.200883,15.942151,18910.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 247782 to 269350
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    100000 non-null  float64
 1   V1      100000 non-null  float64
 2   V2      100000 non-null  float64
 3   V3      100000 non-null  float64
 4   V4      100000 non-null  float64
 5   V5      100000 non-null  float64
 6   V6      100000 non-null  float64
 7   V7      100000 non-null  float64
 8   V8      100000 non-null  float64
 9   V9      100000 non-null  float64
 10  V10     100000 non-null  float64
 11  V11     100000 non-null  float64
 12  V12     100000 non-null  float64
 13  V13     100000 non-null  float64
 14  V14     100000 non-null  float64
 15  V15     100000 non-null  float64
 16  V16     100000 non-null  float64
 17  V17     100000 non-null  float64
 18  V18     100000 non-null  float64
 19  V19     100000 non-null  float64
 20  V20     100000 non-null  float64
 21  V21     100000 non-null  float64
 22  V22     100000 non-null  float64
 23  V23     100000 non-null  float64
 24  V24     100000 non-null  float64
 25  V25     100000 non-null  float64
 26  V26     100000 non-null  float64
 27  V27     100000 non-null  float64
 28  V28     100000 non-null  float64
 29  Amount  100000 non-null  float64
 30  Class   100000 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 24.4 MB

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
247782,153690.0,-1.163878,0.341703,1.267351,0.909800,0.401858,0.225098,-0.578505,0.794419,-0.554942,...,0.440720,0.933170,-0.238406,0.701663,-0.100059,-0.425518,0.082630,-0.022934,0.00,0
178347,123593.0,-0.220355,1.192071,-0.497151,-0.349441,0.216024,-1.280667,0.696175,0.142513,-0.129868,...,0.403019,1.292942,-0.084394,0.006011,-0.769752,-0.214752,0.383104,0.258844,2.33,0
109048,71192.0,0.793973,-0.661427,-0.494583,0.057280,-0.058514,-0.106292,0.383599,0.029120,-0.291140,...,0.173188,0.042804,-0.207411,-0.220839,0.263976,1.093842,-0.129454,0.007654,212.95,0
155965,106889.0,2.001004,0.260455,-1.453785,0.548846,0.532815,-0.589226,0.075159,-0.240541,1.356886,...,-0.433050,-0.909683,0.340644,0.636149,-0.307340,0.099499,-0.088724,-0.041086,12.99,0
114972,73695.0,1.158611,0.132251,0.289231,1.201402,0.023768,0.308631,-0.087959,0.184431,0.138230,...,-0.082353,-0.044418,-0.102405,-0.315629,0.660518,-0.306696,0.033515,-0.000059,1.00,0

In [9]:
df['Class'].value_counts()

Class
0    99818
1      182
Name: count, dtype: int64

In [10]:
X = df.drop("Class",axis=1)
y = df["Class"]

In [11]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [12]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
model1 = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
model1.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [15]:
y_pred1 = model1.predict(X_test)

In [16]:
print("Accuracy:",accuracy_score(y_test,y_pred1))

print("\nClassification Report")
print(classification_report(y_test,y_pred1))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred1))

Accuracy: 0.999

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.85      0.59      0.70        39

    accuracy                           1.00     20000
   macro avg       0.93      0.79      0.85     20000
weighted avg       1.00      1.00      1.00     20000


Confusion Matrix
[[19957     4]
 [   16    23]]

In [17]:
model2 = KNeighborsClassifier(n_neighbors=5,metric='manhattan')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred2))

print("\nClassification Report")
print(classification_report(y_test,y_pred2))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred2))

Accuracy: 0.99895

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.85      0.56      0.68        39

    accuracy                           1.00     20000
   macro avg       0.92      0.78      0.84     20000
weighted avg       1.00      1.00      1.00     20000


Confusion Matrix
[[19957     4]
 [   17    22]]