In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sms

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv('StudentsPerformance.csv')
df.shape

(1000, 8)

In [3]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [5]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [6]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
df = pd.get_dummies(df, drop_first=True)

In [8]:
X = df.drop('math score', axis=1)
y = df['math score']

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
model1 = SVR(kernel='linear')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred1))
print("MAE:",mean_absolute_error(y_test,y_pred1))
print("r2_score",r2_score(y_test,y_pred1))

MSE: 29.13718667520676
MAE: 4.247962730057836
r2_score 0.8802606301545224

In [13]:
model2 = SVR(kernel='rbf')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred2))
print("MAE:",mean_absolute_error(y_test,y_pred2))
print("r2_score",r2_score(y_test,y_pred2))

MSE: 80.3929805654161
MAE: 6.3796210251236865
r2_score 0.6696247671332758

In [14]:
model3 = SVR(kernel='poly')
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred3))
print("MAE:",mean_absolute_error(y_test,y_pred3))
print("r2_score",r2_score(y_test,y_pred3))

MSE: 73.54840507871182
MAE: 6.642459368506423
r2_score 0.6977525738695092

In [15]:
param_grid = {
    'kernel':['rbf','linear'],
    'C':[1,10,100,1000],
    'epsilon':[0.01,0.1,1],
    'gamma':['scale','auto']
}
grid = GridSearchCV(SVR(),param_grid,cv=5,scoring='r2')
grid.fit(X_train,y_train)
print(grid.best_params_)
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
print("R2 Score:",r2_score(y_test,y_pred))

{'C': 10, 'epsilon': 1, 'gamma': 'scale', 'kernel': 'linear'}
R2 Score: 0.8827702121234446