In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [2]:
df = pd.read_csv('houseprice.csv')

In [3]:
df.shape

(1460, 81)

In [4]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
df = df.drop(["Id","PoolQC","MiscFeature","Alley","Fence"], axis=1)

In [8]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [9]:
cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [10]:
df = pd.get_dummies(df,drop_first=True)

In [11]:
df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,False,False,False,False,True,False,False,False,True,False
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,False,False,False,False,True,False,False,False,True,False
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,False,False,False,False,True,False,False,False,True,False
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,False,False,False,False,True,False,False,False,False,False
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,False,False,False,False,True,False,False,False,True,False

In [12]:
X = df.drop('SalePrice',axis=1)
y=df['SalePrice']

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
model1 = AdaBoostRegressor(n_estimators = 100,random_state=42)
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print('MSE:',mean_squared_error(y_test,y_pred1))
print('MAE:',mean_absolute_error(y_test,y_pred1))
print('r2_score:',r2_score(y_test,y_pred1))

MSE: 1332081693.3728838
MAE: 26008.802167358866
r2_score: 0.8263331105625314

In [20]:
model2 = GradientBoostingRegressor()
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print('MSE:',mean_squared_error(y_test,y_pred2))
print('MAE:',mean_absolute_error(y_test,y_pred2))
print('r2_score:',r2_score(y_test,y_pred2))

MSE: 792834233.385639
MAE: 17448.870333297345
r2_score: 0.8966361779186457

In [21]:
model3 = XGBRegressor()
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print('MSE:',mean_squared_error(y_test,y_pred3))
print('MAE:',mean_absolute_error(y_test,y_pred3))
print('r2_score:',r2_score(y_test,y_pred3))

MSE: 797598016.0
MAE: 17800.61328125
r2_score: 0.8960151076316833

In [22]:
model4 = CatBoostRegressor()
model4.fit(X_train,y_train)
y_pred4 = model4.predict(X_test)
print('MSE:',mean_squared_error(y_test,y_pred4))
print('MAE:',mean_absolute_error(y_test,y_pred4))
print('r2_score:',r2_score(y_test,y_pred4))

Learning rate set to 0.04196
0:	learn: 75129.1984324	total: 61.7ms	remaining: 1m 1s
1:	learn: 73159.1219450	total: 69ms	remaining: 34.5s
2:	learn: 71258.0485182	total: 73.7ms	remaining: 24.5s
3:	learn: 69343.2529977	total: 78ms	remaining: 19.4s
4:	learn: 67668.1150813	total: 80.9ms	remaining: 16.1s
5:	learn: 66065.4920636	total: 83.9ms	remaining: 13.9s
6:	learn: 64523.6071172	total: 88.5ms	remaining: 12.6s
7:	learn: 63132.8415304	total: 91.6ms	remaining: 11.4s
8:	learn: 61614.1800154	total: 94ms	remaining: 10.4s
9:	learn: 60198.6765755	total: 97.1ms	remaining: 9.61s
10:	learn: 58765.5077034	total: 99.7ms	remaining: 8.96s
11:	learn: 57365.7230566	total: 103ms	remaining: 8.45s
12:	learn: 56047.6797528	total: 105ms	remaining: 8.01s
13:	learn: 54681.9022145	total: 108ms	remaining: 7.63s
14:	learn: 53445.7478145	total: 110ms	remaining: 7.25s
15:	learn: 52381.8434362	total: 113ms	remaining: 6.95s
16:	learn: 51350.2827522	total: 115ms	remaining: 6.65s
17:	learn: 50450.1479165	total: 117ms	remaining: 6.39s
18:	learn: 49583.9309745	total: 119ms	remaining: 6.16s
19:	learn: 48659.4431552	total: 121ms	remaining: 5.94s
20:	learn: 47729.2472031	total: 123ms	remaining: 5.74s
21:	learn: 46935.2083584	total: 125ms	remaining: 5.56s
22:	learn: 46072.2304921	total: 127ms	remaining: 5.4s
23:	learn: 45213.5099720	total: 129ms	remaining: 5.24s
24:	learn: 44436.0767175	total: 131ms	remaining: 5.11s
25:	learn: 43670.4862925	total: 133ms	remaining: 4.97s
26:	learn: 42856.1564854	total: 135ms	remaining: 4.85s
27:	learn: 42129.7141613	total: 136ms	remaining: 4.73s
28:	learn: 41440.4159987	total: 138ms	remaining: 4.62s
29:	learn: 40750.4424084	total: 140ms	remaining: 4.51s
30:	learn: 40134.6127875	total: 141ms	remaining: 4.42s
31:	learn: 39522.1813229	total: 143ms	remaining: 4.33s
32:	learn: 38944.4904092	total: 145ms	remaining: 4.24s
33:	learn: 38427.5011392	total: 146ms	remaining: 4.16s
34:	learn: 37819.6175860	total: 148ms	remaining: 4.08s
35:	learn: 37231.4158128	total: 150ms	remaining: 4.01s
36:	learn: 36744.0625293	total: 151ms	remaining: 3.94s
37:	learn: 36266.7191922	total: 153ms	remaining: 3.88s
38:	learn: 35792.6694197	total: 155ms	remaining: 3.81s
39:	learn: 35323.1378052	total: 156ms	remaining: 3.75s
40:	learn: 34894.5462629	total: 158ms	remaining: 3.7s
41:	learn: 34408.3290612	total: 160ms	remaining: 3.64s
42:	learn: 34017.2019641	total: 161ms	remaining: 3.59s
43:	learn: 33637.7635383	total: 163ms	remaining: 3.54s
44:	learn: 33240.4730796	total: 164ms	remaining: 3.49s
45:	learn: 32807.6996377	total: 166ms	remaining: 3.45s
46:	learn: 32430.3720347	total: 168ms	remaining: 3.4s
47:	learn: 32047.8515015	total: 169ms	remaining: 3.36s
48:	learn: 31741.4838297	total: 171ms	remaining: 3.32s
49:	learn: 31354.7790242	total: 173ms	remaining: 3.28s
50:	learn: 30974.1980960	total: 174ms	remaining: 3.25s
51:	learn: 30692.6822005	total: 176ms	remaining: 3.21s
52:	learn: 30372.6460411	total: 178ms	remaining: 3.18s
53:	learn: 30055.7150591	total: 180ms	remaining: 3.15s
54:	learn: 29769.9913295	total: 181ms	remaining: 3.11s
55:	learn: 29488.6170100	total: 183ms	remaining: 3.08s
56:	learn: 29198.6515800	total: 185ms	remaining: 3.05s
57:	learn: 28940.1606352	total: 186ms	remaining: 3.02s
58:	learn: 28678.2627550	total: 188ms	remaining: 3s
59:	learn: 28461.0123850	total: 189ms	remaining: 2.97s
60:	learn: 28255.2091573	total: 191ms	remaining: 2.94s
61:	learn: 28014.7591398	total: 193ms	remaining: 2.92s
62:	learn: 27733.8955301	total: 194ms	remaining: 2.89s
63:	learn: 27523.4146885	total: 196ms	remaining: 2.86s
64:	learn: 27274.8500882	total: 198ms	remaining: 2.85s
65:	learn: 27073.5945575	total: 200ms	remaining: 2.82s
66:	learn: 26851.8393364	total: 202ms	remaining: 2.81s
67:	learn: 26634.3198927	total: 203ms	remaining: 2.79s
68:	learn: 26446.8168403	total: 205ms	remaining: 2.76s
69:	learn: 26300.2562985	total: 207ms	remaining: 2.74s
70:	learn: 26129.3136218	total: 209ms	remaining: 2.73s
71:	learn: 25948.8731907	total: 211ms	remaining: 2.71s
72:	learn: 25761.4481590	total: 213ms	remaining: 2.7s
73:	learn: 25580.6134447	total: 214ms	remaining: 2.68s
74:	learn: 25435.4472985	total: 216ms	remaining: 2.66s
75:	learn: 25284.4614056	total: 218ms	remaining: 2.65s
76:	learn: 25096.2731016	total: 220ms	remaining: 2.64s
77:	learn: 24958.0096891	total: 222ms	remaining: 2.62s
78:	learn: 24803.1365604	total: 223ms	remaining: 2.6s
79:	learn: 24695.9657008	total: 225ms	remaining: 2.59s
80:	learn: 24569.6923888	total: 227ms	remaining: 2.57s
81:	learn: 24416.7926348	total: 228ms	remaining: 2.56s
82:	learn: 24297.3050928	total: 230ms	remaining: 2.54s
83:	learn: 24145.1076703	total: 232ms	remaining: 2.52s
84:	learn: 24017.2794361	total: 233ms	remaining: 2.51s
85:	learn: 23901.7301476	total: 235ms	remaining: 2.5s
86:	learn: 23750.4041033	total: 237ms	remaining: 2.49s
87:	learn: 23655.7990000	total: 239ms	remaining: 2.47s
88:	learn: 23583.2918578	total: 240ms	remaining: 2.46s
89:	learn: 23486.7688642	total: 242ms	remaining: 2.44s
90:	learn: 23381.1968678	total: 244ms	remaining: 2.43s
91:	learn: 23275.2165639	total: 245ms	remaining: 2.42s
92:	learn: 23155.9301174	total: 247ms	remaining: 2.41s
93:	learn: 23015.9953352	total: 249ms	remaining: 2.4s
94:	learn: 22869.8778990	total: 251ms	remaining: 2.39s
95:	learn: 22775.2521830	total: 252ms	remaining: 2.37s
96:	learn: 22651.2923757	total: 254ms	remaining: 2.36s
97:	learn: 22548.3985432	total: 255ms	remaining: 2.35s
98:	learn: 22399.3924562	total: 257ms	remaining: 2.34s
99:	learn: 22301.6371171	total: 259ms	remaining: 2.33s
100:	learn: 22209.1068360	total: 260ms	remaining: 2.32s
101:	learn: 22095.2300379	total: 262ms	remaining: 2.31s
102:	learn: 21980.1834078	total: 264ms	remaining: 2.3s
103:	learn: 21887.6169389	total: 265ms	remaining: 2.29s
104:	learn: 21786.0768377	total: 268ms	remaining: 2.28s
105:	learn: 21708.8912141	total: 270ms	remaining: 2.28s
106:	learn: 21618.1937954	total: 272ms	remaining: 2.27s
107:	learn: 21506.2624443	total: 273ms	remaining: 2.26s
108:	learn: 21425.9229804	total: 275ms	remaining: 2.25s
109:	learn: 21346.1921291	total: 276ms	remaining: 2.23s
110:	learn: 21271.9759114	total: 278ms	remaining: 2.23s
111:	learn: 21196.6063567	total: 280ms	remaining: 2.22s
112:	learn: 21107.4948431	total: 281ms	remaining: 2.21s
113:	learn: 21004.8141268	total: 283ms	remaining: 2.2s
114:	learn: 20929.5461403	total: 285ms	remaining: 2.19s
115:	learn: 20847.3765351	total: 286ms	remaining: 2.18s
116:	learn: 20779.4849406	total: 288ms	remaining: 2.17s
117:	learn: 20719.8969065	total: 289ms	remaining: 2.16s
118:	learn: 20650.9300709	total: 291ms	remaining: 2.15s
119:	learn: 20586.0511766	total: 293ms	remaining: 2.15s
120:	learn: 20495.7783780	total: 294ms	remaining: 2.14s
121:	learn: 20422.6430968	total: 296ms	remaining: 2.13s
122:	learn: 20341.2104421	total: 298ms	remaining: 2.12s
123:	learn: 20327.3105856	total: 300ms	remaining: 2.12s
124:	learn: 20273.9040436	total: 301ms	remaining: 2.11s
125:	learn: 20212.3849101	total: 303ms	remaining: 2.1s
126:	learn: 20142.3402980	total: 305ms	remaining: 2.09s
127:	learn: 20079.3418494	total: 306ms	remaining: 2.08s
128:	learn: 20036.8885982	total: 308ms	remaining: 2.08s
129:	learn: 19949.2371495	total: 310ms	remaining: 2.07s
130:	learn: 19895.1210673	total: 311ms	remaining: 2.06s
131:	learn: 19876.1647051	total: 313ms	remaining: 2.06s
132:	learn: 19792.9325270	total: 314ms	remaining: 2.05s
133:	learn: 19711.5396960	total: 316ms	remaining: 2.04s
134:	learn: 19657.1535682	total: 318ms	remaining: 2.03s
135:	learn: 19601.8845394	total: 319ms	remaining: 2.03s
136:	learn: 19541.9514071	total: 321ms	remaining: 2.02s
137:	learn: 19491.0998558	total: 322ms	remaining: 2.01s
138:	learn: 19437.1568926	total: 324ms	remaining: 2s
139:	learn: 19387.6183101	total: 325ms	remaining: 2s
140:	learn: 19342.0328451	total: 327ms	remaining: 1.99s
141:	learn: 19263.2843730	total: 329ms	remaining: 1.99s
142:	learn: 19223.0829862	total: 330ms	remaining: 1.98s
143:	learn: 19201.1180595	total: 332ms	remaining: 1.97s
144:	learn: 19150.1303759	total: 333ms	remaining: 1.97s
145:	learn: 19104.6692005	total: 335ms	remaining: 1.96s
146:	learn: 19049.5908943	total: 337ms	remaining: 1.95s
147:	learn: 18997.7448108	total: 339ms	remaining: 1.95s
148:	learn: 18955.4984160	total: 341ms	remaining: 1.95s
149:	learn: 18907.2128486	total: 343ms	remaining: 1.94s
150:	learn: 18837.0012829	total: 345ms	remaining: 1.94s
151:	learn: 18801.8221668	total: 346ms	remaining: 1.93s
152:	learn: 18761.8906776	total: 348ms	remaining: 1.92s
153:	learn: 18723.9120768	total: 350ms	remaining: 1.92s
154:	learn: 18665.6891008	total: 351ms	remaining: 1.91s
155:	learn: 18616.6765843	total: 353ms	remaining: 1.91s
156:	learn: 18559.8842256	total: 354ms	remaining: 1.9s
157:	learn: 18527.7132712	total: 356ms	remaining: 1.9s
158:	learn: 18475.1163564	total: 358ms	remaining: 1.89s
159:	learn: 18412.3425479	total: 359ms	remaining: 1.89s
160:	learn: 18348.5129928	total: 362ms	remaining: 1.88s
161:	learn: 18304.8644424	total: 363ms	remaining: 1.88s
162:	learn: 18242.8990370	total: 365ms	remaining: 1.87s
163:	learn: 18182.2518846	total: 367ms	remaining: 1.87s
164:	learn: 18155.3155824	total: 368ms	remaining: 1.86s
165:	learn: 18133.6144437	total: 369ms	remaining: 1.85s
166:	learn: 18088.0566345	total: 370ms	remaining: 1.85s
167:	learn: 18044.5213590	total: 372ms	remaining: 1.84s
168:	learn: 18008.4988731	total: 374ms	remaining: 1.84s
169:	learn: 17964.9757351	total: 375ms	remaining: 1.83s
170:	learn: 17912.0488251	total: 377ms	remaining: 1.83s
171:	learn: 17851.9787105	total: 379ms	remaining: 1.82s
172:	learn: 17810.8029611	total: 380ms	remaining: 1.82s
173:	learn: 17789.0450283	total: 382ms	remaining: 1.81s
174:	learn: 17729.0446635	total: 383ms	remaining: 1.81s
175:	learn: 17705.6015352	total: 385ms	remaining: 1.8s
176:	learn: 17643.1294297	total: 387ms	remaining: 1.8s
177:	learn: 17603.0512616	total: 388ms	remaining: 1.79s
178:	learn: 17554.3237561	total: 390ms	remaining: 1.79s
179:	learn: 17517.8102220	total: 391ms	remaining: 1.78s
180:	learn: 17486.3057938	total: 393ms	remaining: 1.78s
181:	learn: 17453.7326692	total: 395ms	remaining: 1.77s
182:	learn: 17394.2773431	total: 397ms	remaining: 1.77s
183:	learn: 17376.6963906	total: 398ms	remaining: 1.77s
184:	learn: 17331.0649555	total: 400ms	remaining: 1.76s
185:	learn: 17314.8695110	total: 400ms	remaining: 1.75s
186:	learn: 17272.1312068	total: 402ms	remaining: 1.75s
187:	learn: 17262.3501645	total: 404ms	remaining: 1.74s
188:	learn: 17225.6865380	total: 406ms	remaining: 1.74s
189:	learn: 17215.1757944	total: 407ms	remaining: 1.74s
190:	learn: 17149.7464467	total: 409ms	remaining: 1.73s
191:	learn: 17112.8234947	total: 430ms	remaining: 1.81s
192:	learn: 17099.0044022	total: 431ms	remaining: 1.8s
193:	learn: 17055.9014106	total: 433ms	remaining: 1.8s
194:	learn: 17011.8549894	total: 440ms	remaining: 1.81s
195:	learn: 16998.7268776	total: 440ms	remaining: 1.8s
196:	learn: 16986.1695193	total: 442ms	remaining: 1.8s
197:	learn: 16973.8165874	total: 443ms	remaining: 1.79s
198:	learn: 16922.2157129	total: 444ms	remaining: 1.79s
199:	learn: 16851.3703745	total: 446ms	remaining: 1.78s
200:	learn: 16818.9113884	total: 448ms	remaining: 1.78s
201:	learn: 16780.0975271	total: 449ms	remaining: 1.77s
202:	learn: 16726.9141357	total: 451ms	remaining: 1.77s
203:	learn: 16715.6549868	total: 453ms	remaining: 1.77s
204:	learn: 16686.3801946	total: 455ms	remaining: 1.76s
205:	learn: 16650.3710548	total: 456ms	remaining: 1.76s
206:	learn: 16640.0509663	total: 457ms	remaining: 1.75s
207:	learn: 16612.6231814	total: 458ms	remaining: 1.75s
208:	learn: 16560.9956884	total: 460ms	remaining: 1.74s
209:	learn: 16528.4974014	total: 462ms	remaining: 1.74s
210:	learn: 16489.0617962	total: 464ms	remaining: 1.73s
211:	learn: 16448.9328200	total: 466ms	remaining: 1.73s
212:	learn: 16407.4545460	total: 467ms	remaining: 1.73s
213:	learn: 16365.4887381	total: 469ms	remaining: 1.72s
214:	learn: 16351.1196638	total: 470ms	remaining: 1.72s
215:	learn: 16316.2843601	total: 472ms	remaining: 1.71s
216:	learn: 16304.9874159	total: 473ms	remaining: 1.71s
217:	learn: 16266.4058375	total: 475ms	remaining: 1.7s
218:	learn: 16231.4763617	total: 477ms	remaining: 1.7s
219:	learn: 16186.0916619	total: 479ms	remaining: 1.7s
220:	learn: 16148.7855242	total: 480ms	remaining: 1.69s
221:	learn: 16100.6201252	total: 482ms	remaining: 1.69s
222:	learn: 16061.0269495	total: 484ms	remaining: 1.69s
223:	learn: 16011.3443009	total: 486ms	remaining: 1.68s
224:	learn: 16000.8372140	total: 487ms	remaining: 1.68s
225:	learn: 15974.6997774	total: 489ms	remaining: 1.68s
226:	learn: 15938.4340350	total: 491ms	remaining: 1.67s
227:	learn: 15910.8801314	total: 492ms	remaining: 1.67s
228:	learn: 15872.9249423	total: 494ms	remaining: 1.66s
229:	learn: 15831.3874706	total: 496ms	remaining: 1.66s
230:	learn: 15777.5152319	total: 497ms	remaining: 1.66s
231:	learn: 15769.8205291	total: 499ms	remaining: 1.65s
232:	learn: 15723.9769036	total: 501ms	remaining: 1.65s
233:	learn: 15689.7605155	total: 502ms	remaining: 1.64s
234:	learn: 15647.3970050	total: 504ms	remaining: 1.64s
235:	learn: 15640.1287556	total: 505ms	remaining: 1.64s
236:	learn: 15599.7268659	total: 507ms	remaining: 1.63s
237:	learn: 15590.9461059	total: 508ms	remaining: 1.63s
238:	learn: 15555.0696611	total: 510ms	remaining: 1.62s
239:	learn: 15517.1289470	total: 512ms	remaining: 1.62s
240:	learn: 15491.0435494	total: 513ms	remaining: 1.62s
241:	learn: 15455.4217173	total: 515ms	remaining: 1.61s
242:	learn: 15410.9691266	total: 517ms	remaining: 1.61s
243:	learn: 15377.3554066	total: 519ms	remaining: 1.61s
244:	learn: 15331.3345998	total: 521ms	remaining: 1.6s
245:	learn: 15291.0880002	total: 522ms	remaining: 1.6s
246:	learn: 15284.8396532	total: 524ms	remaining: 1.6s
247:	learn: 15247.5670959	total: 526ms	remaining: 1.59s
248:	learn: 15214.5996269	total: 527ms	remaining: 1.59s
249:	learn: 15183.3425834	total: 529ms	remaining: 1.59s
250:	learn: 15166.8218498	total: 531ms	remaining: 1.58s
251:	learn: 15144.4433445	total: 533ms	remaining: 1.58s
252:	learn: 15108.3033197	total: 534ms	remaining: 1.58s
253:	learn: 15075.8051573	total: 536ms	remaining: 1.57s
254:	learn: 15058.8195476	total: 537ms	remaining: 1.57s
255:	learn: 15043.9862035	total: 539ms	remaining: 1.56s
256:	learn: 15002.5456349	total: 541ms	remaining: 1.56s
257:	learn: 14952.2857816	total: 542ms	remaining: 1.56s
258:	learn: 14918.0314987	total: 544ms	remaining: 1.56s
259:	learn: 14879.6132343	total: 546ms	remaining: 1.55s
260:	learn: 14836.8037422	total: 548ms	remaining: 1.55s
261:	learn: 14812.3743114	total: 549ms	remaining: 1.55s
262:	learn: 14775.6002466	total: 551ms	remaining: 1.54s
263:	learn: 14750.1977715	total: 552ms	remaining: 1.54s
264:	learn: 14707.5891662	total: 554ms	remaining: 1.54s
265:	learn: 14684.7844619	total: 556ms	remaining: 1.53s
266:	learn: 14660.1829685	total: 557ms	remaining: 1.53s
267:	learn: 14614.3601679	total: 559ms	remaining: 1.53s
268:	learn: 14576.1796332	total: 561ms	remaining: 1.52s
269:	learn: 14548.4023273	total: 563ms	remaining: 1.52s
270:	learn: 14507.5797110	total: 565ms	remaining: 1.52s
271:	learn: 14495.4976902	total: 566ms	remaining: 1.51s
272:	learn: 14470.2415620	total: 568ms	remaining: 1.51s
273:	learn: 14438.8156889	total: 570ms	remaining: 1.51s
274:	learn: 14406.6367108	total: 571ms	remaining: 1.51s
275:	learn: 14386.3459938	total: 573ms	remaining: 1.5s
276:	learn: 14362.0144275	total: 575ms	remaining: 1.5s
277:	learn: 14328.5922347	total: 576ms	remaining: 1.5s
278:	learn: 14311.7720926	total: 578ms	remaining: 1.49s
279:	learn: 14277.7384217	total: 580ms	remaining: 1.49s
280:	learn: 14261.3482759	total: 582ms	remaining: 1.49s
281:	learn: 14228.2437074	total: 584ms	remaining: 1.49s
282:	learn: 14188.8000453	total: 585ms	remaining: 1.48s
283:	learn: 14160.6788212	total: 587ms	remaining: 1.48s
284:	learn: 14156.8541652	total: 588ms	remaining: 1.48s
285:	learn: 14136.5423432	total: 590ms	remaining: 1.47s
286:	learn: 14113.1999286	total: 592ms	remaining: 1.47s
287:	learn: 14090.2642996	total: 594ms	remaining: 1.47s
288:	learn: 14065.8340984	total: 596ms	remaining: 1.47s
289:	learn: 14042.1164603	total: 598ms	remaining: 1.46s
290:	learn: 14023.3285976	total: 599ms	remaining: 1.46s
291:	learn: 14000.3101510	total: 602ms	remaining: 1.46s
292:	learn: 13972.4028060	total: 603ms	remaining: 1.46s
293:	learn: 13933.8147336	total: 606ms	remaining: 1.45s
294:	learn: 13904.2525485	total: 607ms	remaining: 1.45s
295:	learn: 13881.4917765	total: 609ms	remaining: 1.45s
296:	learn: 13877.6510478	total: 611ms	remaining: 1.45s
297:	learn: 13847.7084158	total: 613ms	remaining: 1.44s
298:	learn: 13828.5858249	total: 615ms	remaining: 1.44s
299:	learn: 13795.1443637	total: 616ms	remaining: 1.44s
300:	learn: 13791.5392674	total: 618ms	remaining: 1.44s
301:	learn: 13788.2655810	total: 620ms	remaining: 1.43s
302:	learn: 13768.9142588	total: 622ms	remaining: 1.43s
303:	learn: 13753.2942466	total: 623ms	remaining: 1.43s
304:	learn: 13723.3883386	total: 625ms	remaining: 1.42s
305:	learn: 13710.1926270	total: 627ms	remaining: 1.42s
306:	learn: 13684.6619164	total: 629ms	remaining: 1.42s
307:	learn: 13670.4140420	total: 631ms	remaining: 1.42s
308:	learn: 13655.5642714	total: 632ms	remaining: 1.41s
309:	learn: 13625.8997684	total: 634ms	remaining: 1.41s
310:	learn: 13622.3393867	total: 636ms	remaining: 1.41s
311:	learn: 13602.2467309	total: 638ms	remaining: 1.41s
312:	learn: 13568.7709975	total: 639ms	remaining: 1.4s
313:	learn: 13537.6397955	total: 641ms	remaining: 1.4s
314:	learn: 13517.0574668	total: 643ms	remaining: 1.4s
315:	learn: 13493.5609993	total: 645ms	remaining: 1.4s
316:	learn: 13467.1478758	total: 646ms	remaining: 1.39s
317:	learn: 13437.1019317	total: 648ms	remaining: 1.39s
318:	learn: 13414.7001281	total: 650ms	remaining: 1.39s
319:	learn: 13399.8377485	total: 651ms	remaining: 1.38s
320:	learn: 13391.2071309	total: 653ms	remaining: 1.38s
321:	learn: 13377.7556510	total: 655ms	remaining: 1.38s
322:	learn: 13374.5174453	total: 656ms	remaining: 1.37s
323:	learn: 13371.5585203	total: 658ms	remaining: 1.37s
324:	learn: 13346.0940528	total: 660ms	remaining: 1.37s
325:	learn: 13330.5441808	total: 661ms	remaining: 1.37s
326:	learn: 13310.5256637	total: 663ms	remaining: 1.36s
327:	learn: 13307.8772950	total: 665ms	remaining: 1.36s
328:	learn: 13290.2946533	total: 666ms	remaining: 1.36s
329:	learn: 13272.2121256	total: 668ms	remaining: 1.36s
330:	learn: 13255.9648534	total: 670ms	remaining: 1.35s
331:	learn: 13244.5680851	total: 671ms	remaining: 1.35s
332:	learn: 13241.5998442	total: 673ms	remaining: 1.35s
333:	learn: 13221.3218059	total: 674ms	remaining: 1.34s
334:	learn: 13190.0611519	total: 676ms	remaining: 1.34s
335:	learn: 13170.6020588	total: 678ms	remaining: 1.34s
336:	learn: 13140.5164737	total: 680ms	remaining: 1.34s
337:	learn: 13126.8247354	total: 681ms	remaining: 1.33s
338:	learn: 13107.1029865	total: 683ms	remaining: 1.33s
339:	learn: 13088.7535034	total: 685ms	remaining: 1.33s
340:	learn: 13060.5880548	total: 687ms	remaining: 1.33s
341:	learn: 13030.9964754	total: 689ms	remaining: 1.32s
342:	learn: 12994.6812763	total: 690ms	remaining: 1.32s
343:	learn: 12963.9716570	total: 692ms	remaining: 1.32s
344:	learn: 12945.5623516	total: 694ms	remaining: 1.32s
345:	learn: 12935.4388913	total: 695ms	remaining: 1.31s
346:	learn: 12914.4531953	total: 697ms	remaining: 1.31s
347:	learn: 12879.4548485	total: 699ms	remaining: 1.31s
348:	learn: 12862.7772143	total: 700ms	remaining: 1.31s
349:	learn: 12845.2237341	total: 702ms	remaining: 1.3s
350:	learn: 12839.6557400	total: 704ms	remaining: 1.3s
351:	learn: 12799.7503643	total: 706ms	remaining: 1.3s
352:	learn: 12759.6039534	total: 707ms	remaining: 1.3s
353:	learn: 12742.6648560	total: 709ms	remaining: 1.29s
354:	learn: 12719.5601490	total: 711ms	remaining: 1.29s
355:	learn: 12711.5075438	total: 712ms	remaining: 1.29s
356:	learn: 12697.7538609	total: 714ms	remaining: 1.28s
357:	learn: 12668.5755665	total: 716ms	remaining: 1.28s
358:	learn: 12647.7574103	total: 718ms	remaining: 1.28s

In [23]:
model5 = LGBMRegressor()
model5.fit(X_train,y_train)
y_pred5 = model5.predict(X_test)
print('MSE:',mean_squared_error(y_test,y_pred5))
print('MAE:',mean_absolute_error(y_test,y_pred5))
print('r2_score:',r2_score(y_test,y_pred5))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001818 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3134
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 151
[LightGBM] [Info] Start training from score 181441.541952
MSE: 879633055.2418954
MAE: 17068.12440668908
r2_score: 0.8853199940287186