In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.drop(['Id'],axis=1,inplace=True)

In [7]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [9]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [10]:
df.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
count     150.000000    150.000000     150.000000    150.000000  150.000000
mean        5.843333      3.054000       3.758667      1.198667    1.000000
std         0.828066      0.433594       1.764420      0.763161    0.819232
min         4.300000      2.000000       1.000000      0.100000    0.000000
25%         5.100000      2.800000       1.600000      0.300000    0.000000
50%         5.800000      3.000000       4.350000      1.300000    1.000000
75%         6.400000      3.300000       5.100000      1.800000    2.000000
max         7.900000      4.400000       6.900000      2.500000    2.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [12]:
df.shape

(150, 5)

In [13]:
X = df.drop('Species',axis=1)
y = df['Species']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
model1 = AdaBoostClassifier(random_state=42)
model1.fit(X_train,y_train)
y_pred1=model1.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print("confusion_matrix:",confusion_matrix(y_test,y_pred1))

accuracy_Score: 0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.89      0.89         9
           2       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

confusion_matrix: [[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]

In [16]:
model2 = GradientBoostingClassifier()
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))
print("confusion_matrix:",confusion_matrix(y_test,y_pred2))

accuracy_Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [17]:
model3 = XGBClassifier()
model3.fit(X_train,y_train)
y_pred3=model3.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))
print("confusion_matrix:",confusion_matrix(y_test,y_pred3))

accuracy_Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [18]:
model4 = CatBoostClassifier()
model4.fit(X_train,y_train)
y_pred4=model4.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred4))
print(classification_report(y_test,y_pred4))
print("confusion_matrix:",confusion_matrix(y_test,y_pred4))

Learning rate set to 0.071017
0:	learn: 1.0144505	total: 59.5ms	remaining: 59.5s
1:	learn: 0.9426321	total: 60.1ms	remaining: 30s
2:	learn: 0.8791473	total: 60.5ms	remaining: 20.1s
3:	learn: 0.8214933	total: 60.9ms	remaining: 15.2s
4:	learn: 0.7788401	total: 61.6ms	remaining: 12.3s
5:	learn: 0.7280627	total: 61.8ms	remaining: 10.2s
6:	learn: 0.6913500	total: 62ms	remaining: 8.79s
7:	learn: 0.6584766	total: 62.2ms	remaining: 7.71s
8:	learn: 0.6235636	total: 62.5ms	remaining: 6.88s
9:	learn: 0.5948198	total: 62.9ms	remaining: 6.23s
10:	learn: 0.5645192	total: 63.1ms	remaining: 5.67s
11:	learn: 0.5372072	total: 63.3ms	remaining: 5.21s
12:	learn: 0.5124436	total: 63.5ms	remaining: 4.82s
13:	learn: 0.4845248	total: 63.6ms	remaining: 4.48s
14:	learn: 0.4639622	total: 63.9ms	remaining: 4.2s
15:	learn: 0.4432597	total: 64.1ms	remaining: 3.94s
16:	learn: 0.4251080	total: 64.3ms	remaining: 3.72s
17:	learn: 0.4095535	total: 64.6ms	remaining: 3.52s
18:	learn: 0.3929013	total: 64.8ms	remaining: 3.35s
19:	learn: 0.3776665	total: 65ms	remaining: 3.18s
20:	learn: 0.3628192	total: 65.2ms	remaining: 3.04s
21:	learn: 0.3529267	total: 65.3ms	remaining: 2.9s
22:	learn: 0.3424003	total: 65.6ms	remaining: 2.79s
23:	learn: 0.3313127	total: 65.8ms	remaining: 2.67s
24:	learn: 0.3196457	total: 66ms	remaining: 2.57s
25:	learn: 0.3109393	total: 66.2ms	remaining: 2.48s
26:	learn: 0.2995277	total: 66.4ms	remaining: 2.39s
27:	learn: 0.2897103	total: 66.6ms	remaining: 2.31s
28:	learn: 0.2798488	total: 66.7ms	remaining: 2.23s
29:	learn: 0.2715956	total: 66.9ms	remaining: 2.16s
30:	learn: 0.2610148	total: 67ms	remaining: 2.1s
31:	learn: 0.2537267	total: 67.3ms	remaining: 2.03s
32:	learn: 0.2453006	total: 67.5ms	remaining: 1.98s
33:	learn: 0.2392460	total: 67.8ms	remaining: 1.92s
34:	learn: 0.2317634	total: 67.9ms	remaining: 1.87s
35:	learn: 0.2260523	total: 68.1ms	remaining: 1.82s
36:	learn: 0.2210930	total: 68.3ms	remaining: 1.78s
37:	learn: 0.2145211	total: 68.5ms	remaining: 1.74s
38:	learn: 0.2100944	total: 68.7ms	remaining: 1.69s
39:	learn: 0.2046089	total: 68.9ms	remaining: 1.65s
40:	learn: 0.2006331	total: 69.2ms	remaining: 1.62s
41:	learn: 0.1949985	total: 69.4ms	remaining: 1.58s
42:	learn: 0.1899704	total: 69.6ms	remaining: 1.55s
43:	learn: 0.1852009	total: 69.8ms	remaining: 1.52s
44:	learn: 0.1808673	total: 70ms	remaining: 1.49s
45:	learn: 0.1775496	total: 70.2ms	remaining: 1.45s
46:	learn: 0.1734428	total: 70.3ms	remaining: 1.43s
47:	learn: 0.1697240	total: 70.5ms	remaining: 1.4s
48:	learn: 0.1672052	total: 70.7ms	remaining: 1.37s
49:	learn: 0.1634417	total: 70.8ms	remaining: 1.34s
50:	learn: 0.1596705	total: 71.1ms	remaining: 1.32s
51:	learn: 0.1567804	total: 71.2ms	remaining: 1.3s
52:	learn: 0.1539521	total: 71.4ms	remaining: 1.28s
53:	learn: 0.1521546	total: 71.7ms	remaining: 1.25s
54:	learn: 0.1490136	total: 71.9ms	remaining: 1.23s
55:	learn: 0.1454814	total: 72.1ms	remaining: 1.22s
56:	learn: 0.1436783	total: 72.3ms	remaining: 1.2s
57:	learn: 0.1408012	total: 72.5ms	remaining: 1.18s
58:	learn: 0.1379105	total: 72.7ms	remaining: 1.16s
59:	learn: 0.1360634	total: 72.9ms	remaining: 1.14s
60:	learn: 0.1338672	total: 73.1ms	remaining: 1.13s
61:	learn: 0.1317237	total: 73.3ms	remaining: 1.11s
62:	learn: 0.1291975	total: 73.5ms	remaining: 1.09s
63:	learn: 0.1262994	total: 73.7ms	remaining: 1.08s
64:	learn: 0.1243073	total: 73.9ms	remaining: 1.06s
65:	learn: 0.1223597	total: 74.1ms	remaining: 1.05s
66:	learn: 0.1201234	total: 74.4ms	remaining: 1.03s
67:	learn: 0.1177066	total: 74.6ms	remaining: 1.02s
68:	learn: 0.1159848	total: 74.8ms	remaining: 1.01s
69:	learn: 0.1138786	total: 75ms	remaining: 997ms
70:	learn: 0.1119377	total: 75.2ms	remaining: 984ms
71:	learn: 0.1098407	total: 75.4ms	remaining: 972ms
72:	learn: 0.1084551	total: 75.7ms	remaining: 961ms
73:	learn: 0.1069277	total: 76ms	remaining: 951ms
74:	learn: 0.1053430	total: 76.2ms	remaining: 940ms
75:	learn: 0.1037201	total: 76.4ms	remaining: 929ms
76:	learn: 0.1023445	total: 76.6ms	remaining: 918ms
77:	learn: 0.1009928	total: 76.8ms	remaining: 908ms
78:	learn: 0.0996949	total: 77ms	remaining: 897ms
79:	learn: 0.0983379	total: 77.2ms	remaining: 887ms
80:	learn: 0.0970806	total: 77.4ms	remaining: 878ms
81:	learn: 0.0960735	total: 77.6ms	remaining: 868ms
82:	learn: 0.0947230	total: 77.7ms	remaining: 859ms
83:	learn: 0.0933381	total: 77.9ms	remaining: 850ms
84:	learn: 0.0922599	total: 78.2ms	remaining: 841ms
85:	learn: 0.0910947	total: 78.5ms	remaining: 834ms
86:	learn: 0.0899980	total: 78.7ms	remaining: 826ms
87:	learn: 0.0889163	total: 79ms	remaining: 818ms
88:	learn: 0.0879233	total: 79.2ms	remaining: 811ms
89:	learn: 0.0862256	total: 79.4ms	remaining: 802ms
90:	learn: 0.0853643	total: 79.6ms	remaining: 795ms
91:	learn: 0.0843889	total: 79.7ms	remaining: 787ms
92:	learn: 0.0835035	total: 80ms	remaining: 780ms
93:	learn: 0.0825138	total: 80.2ms	remaining: 773ms
94:	learn: 0.0809737	total: 80.4ms	remaining: 766ms
95:	learn: 0.0797927	total: 80.6ms	remaining: 759ms
96:	learn: 0.0789065	total: 80.8ms	remaining: 752ms
97:	learn: 0.0780194	total: 81ms	remaining: 745ms
98:	learn: 0.0772124	total: 81.2ms	remaining: 739ms
99:	learn: 0.0763884	total: 81.3ms	remaining: 732ms
100:	learn: 0.0754549	total: 81.6ms	remaining: 726ms
101:	learn: 0.0744221	total: 81.8ms	remaining: 720ms
102:	learn: 0.0732983	total: 82ms	remaining: 714ms
103:	learn: 0.0722867	total: 82.2ms	remaining: 708ms
104:	learn: 0.0713782	total: 82.4ms	remaining: 702ms
105:	learn: 0.0705984	total: 82.6ms	remaining: 696ms
106:	learn: 0.0696216	total: 82.8ms	remaining: 691ms
107:	learn: 0.0686591	total: 83.1ms	remaining: 686ms
108:	learn: 0.0678346	total: 83.3ms	remaining: 681ms
109:	learn: 0.0672116	total: 83.5ms	remaining: 676ms
110:	learn: 0.0666274	total: 83.7ms	remaining: 671ms
111:	learn: 0.0658088	total: 84ms	remaining: 666ms
112:	learn: 0.0650954	total: 84.2ms	remaining: 661ms
113:	learn: 0.0641037	total: 84.4ms	remaining: 656ms
114:	learn: 0.0633959	total: 84.7ms	remaining: 652ms
115:	learn: 0.0625268	total: 84.9ms	remaining: 647ms
116:	learn: 0.0618286	total: 85.1ms	remaining: 642ms
117:	learn: 0.0612409	total: 85.3ms	remaining: 637ms
118:	learn: 0.0606553	total: 85.5ms	remaining: 633ms
119:	learn: 0.0600376	total: 85.6ms	remaining: 628ms
120:	learn: 0.0594214	total: 85.8ms	remaining: 624ms
121:	learn: 0.0585415	total: 86.1ms	remaining: 619ms
122:	learn: 0.0576637	total: 86.3ms	remaining: 615ms
123:	learn: 0.0569141	total: 86.5ms	remaining: 611ms
124:	learn: 0.0564459	total: 86.7ms	remaining: 607ms
125:	learn: 0.0556740	total: 86.9ms	remaining: 603ms
126:	learn: 0.0552165	total: 87.1ms	remaining: 599ms
127:	learn: 0.0547061	total: 87.9ms	remaining: 599ms
128:	learn: 0.0540971	total: 88.1ms	remaining: 595ms
129:	learn: 0.0536046	total: 88.3ms	remaining: 591ms
130:	learn: 0.0532235	total: 88.4ms	remaining: 587ms
131:	learn: 0.0526565	total: 88.6ms	remaining: 583ms
132:	learn: 0.0522590	total: 88.8ms	remaining: 579ms
133:	learn: 0.0516285	total: 89ms	remaining: 575ms
134:	learn: 0.0510859	total: 89.3ms	remaining: 572ms
135:	learn: 0.0507234	total: 89.5ms	remaining: 568ms
136:	learn: 0.0501588	total: 89.6ms	remaining: 565ms
137:	learn: 0.0496569	total: 89.8ms	remaining: 561ms
138:	learn: 0.0492332	total: 90ms	remaining: 558ms
139:	learn: 0.0486917	total: 90.2ms	remaining: 554ms
140:	learn: 0.0482020	total: 90.4ms	remaining: 551ms
141:	learn: 0.0478498	total: 90.6ms	remaining: 548ms
142:	learn: 0.0474047	total: 90.9ms	remaining: 545ms
143:	learn: 0.0470068	total: 91.1ms	remaining: 542ms
144:	learn: 0.0465982	total: 92ms	remaining: 542ms
145:	learn: 0.0462319	total: 92.2ms	remaining: 539ms
146:	learn: 0.0457617	total: 92.4ms	remaining: 536ms
147:	learn: 0.0454018	total: 92.6ms	remaining: 533ms
148:	learn: 0.0449552	total: 92.8ms	remaining: 530ms
149:	learn: 0.0445405	total: 93ms	remaining: 527ms
150:	learn: 0.0441888	total: 93.2ms	remaining: 524ms
151:	learn: 0.0438297	total: 93.4ms	remaining: 521ms
152:	learn: 0.0434885	total: 93.7ms	remaining: 519ms
153:	learn: 0.0430993	total: 93.8ms	remaining: 515ms
154:	learn: 0.0427135	total: 94.1ms	remaining: 513ms
155:	learn: 0.0424193	total: 94.3ms	remaining: 510ms
156:	learn: 0.0420601	total: 94.6ms	remaining: 508ms
157:	learn: 0.0416843	total: 94.8ms	remaining: 505ms
158:	learn: 0.0413896	total: 95ms	remaining: 503ms
159:	learn: 0.0409175	total: 95.2ms	remaining: 500ms
160:	learn: 0.0405844	total: 95.4ms	remaining: 497ms
161:	learn: 0.0403382	total: 95.6ms	remaining: 495ms
162:	learn: 0.0400680	total: 95.8ms	remaining: 492ms
163:	learn: 0.0397570	total: 96ms	remaining: 489ms
164:	learn: 0.0393686	total: 96.2ms	remaining: 487ms
165:	learn: 0.0391280	total: 96.4ms	remaining: 484ms
166:	learn: 0.0388939	total: 96.6ms	remaining: 482ms
167:	learn: 0.0386306	total: 96.8ms	remaining: 480ms
168:	learn: 0.0382505	total: 97.1ms	remaining: 477ms
169:	learn: 0.0379387	total: 97.2ms	remaining: 475ms
170:	learn: 0.0376883	total: 97.4ms	remaining: 472ms
171:	learn: 0.0373250	total: 97.7ms	remaining: 470ms
172:	learn: 0.0371129	total: 97.9ms	remaining: 468ms
173:	learn: 0.0368909	total: 98.1ms	remaining: 466ms
174:	learn: 0.0366002	total: 98.3ms	remaining: 463ms
175:	learn: 0.0362143	total: 98.5ms	remaining: 461ms
176:	learn: 0.0359139	total: 98.7ms	remaining: 459ms
177:	learn: 0.0357523	total: 98.9ms	remaining: 457ms
178:	learn: 0.0355318	total: 99.1ms	remaining: 454ms
179:	learn: 0.0353036	total: 99.3ms	remaining: 452ms
180:	learn: 0.0349837	total: 99.5ms	remaining: 450ms
181:	learn: 0.0347458	total: 99.7ms	remaining: 448ms
182:	learn: 0.0344972	total: 99.9ms	remaining: 446ms
183:	learn: 0.0342754	total: 100ms	remaining: 444ms
184:	learn: 0.0340657	total: 100ms	remaining: 442ms
185:	learn: 0.0338205	total: 100ms	remaining: 440ms
186:	learn: 0.0335800	total: 101ms	remaining: 438ms
187:	learn: 0.0333722	total: 101ms	remaining: 436ms
188:	learn: 0.0331627	total: 101ms	remaining: 434ms
189:	learn: 0.0329162	total: 101ms	remaining: 432ms
190:	learn: 0.0327490	total: 102ms	remaining: 430ms
191:	learn: 0.0325031	total: 102ms	remaining: 428ms
192:	learn: 0.0323255	total: 102ms	remaining: 426ms
193:	learn: 0.0320865	total: 102ms	remaining: 425ms
194:	learn: 0.0319283	total: 102ms	remaining: 423ms
195:	learn: 0.0317531	total: 103ms	remaining: 421ms
196:	learn: 0.0315514	total: 103ms	remaining: 419ms
197:	learn: 0.0313364	total: 103ms	remaining: 417ms
198:	learn: 0.0311786	total: 103ms	remaining: 416ms
199:	learn: 0.0309985	total: 104ms	remaining: 414ms
200:	learn: 0.0308250	total: 104ms	remaining: 413ms
201:	learn: 0.0306702	total: 104ms	remaining: 411ms
202:	learn: 0.0305096	total: 104ms	remaining: 409ms
203:	learn: 0.0303139	total: 104ms	remaining: 408ms
204:	learn: 0.0301676	total: 105ms	remaining: 406ms
205:	learn: 0.0299698	total: 105ms	remaining: 404ms
206:	learn: 0.0298410	total: 105ms	remaining: 403ms
207:	learn: 0.0295999	total: 105ms	remaining: 401ms
208:	learn: 0.0295073	total: 106ms	remaining: 400ms
209:	learn: 0.0293382	total: 106ms	remaining: 398ms
210:	learn: 0.0291723	total: 106ms	remaining: 396ms
211:	learn: 0.0289801	total: 106ms	remaining: 395ms
212:	learn: 0.0288439	total: 107ms	remaining: 394ms
213:	learn: 0.0287270	total: 107ms	remaining: 392ms
214:	learn: 0.0285984	total: 107ms	remaining: 390ms
215:	learn: 0.0284462	total: 107ms	remaining: 389ms
216:	learn: 0.0283156	total: 107ms	remaining: 387ms
217:	learn: 0.0280918	total: 108ms	remaining: 386ms
218:	learn: 0.0279422	total: 108ms	remaining: 384ms
219:	learn: 0.0277833	total: 108ms	remaining: 383ms
220:	learn: 0.0276646	total: 108ms	remaining: 381ms
221:	learn: 0.0274939	total: 108ms	remaining: 380ms
222:	learn: 0.0273534	total: 109ms	remaining: 378ms
223:	learn: 0.0272055	total: 109ms	remaining: 377ms
224:	learn: 0.0270826	total: 109ms	remaining: 375ms
225:	learn: 0.0269378	total: 109ms	remaining: 374ms
226:	learn: 0.0267992	total: 109ms	remaining: 372ms
227:	learn: 0.0266827	total: 110ms	remaining: 371ms
228:	learn: 0.0265626	total: 110ms	remaining: 369ms
229:	learn: 0.0264446	total: 110ms	remaining: 368ms
230:	learn: 0.0262620	total: 110ms	remaining: 367ms
231:	learn: 0.0261734	total: 110ms	remaining: 365ms
232:	learn: 0.0259785	total: 111ms	remaining: 364ms
233:	learn: 0.0258391	total: 111ms	remaining: 363ms
234:	learn: 0.0256946	total: 111ms	remaining: 361ms
235:	learn: 0.0255774	total: 111ms	remaining: 360ms
236:	learn: 0.0254277	total: 111ms	remaining: 359ms
237:	learn: 0.0252792	total: 112ms	remaining: 357ms
238:	learn: 0.0251834	total: 112ms	remaining: 356ms
239:	learn: 0.0250533	total: 112ms	remaining: 355ms
240:	learn: 0.0249303	total: 112ms	remaining: 353ms
241:	learn: 0.0248086	total: 112ms	remaining: 352ms
242:	learn: 0.0247085	total: 113ms	remaining: 351ms
243:	learn: 0.0245978	total: 113ms	remaining: 349ms
244:	learn: 0.0244885	total: 113ms	remaining: 348ms
245:	learn: 0.0243565	total: 113ms	remaining: 346ms
246:	learn: 0.0242431	total: 113ms	remaining: 345ms
247:	learn: 0.0240994	total: 113ms	remaining: 344ms
248:	learn: 0.0240006	total: 114ms	remaining: 343ms
249:	learn: 0.0238721	total: 114ms	remaining: 342ms
250:	learn: 0.0237491	total: 114ms	remaining: 340ms
251:	learn: 0.0236635	total: 114ms	remaining: 339ms
252:	learn: 0.0235702	total: 115ms	remaining: 338ms
253:	learn: 0.0234483	total: 115ms	remaining: 337ms
254:	learn: 0.0233239	total: 115ms	remaining: 336ms
255:	learn: 0.0232257	total: 115ms	remaining: 335ms
256:	learn: 0.0230907	total: 115ms	remaining: 334ms
257:	learn: 0.0229923	total: 116ms	remaining: 333ms
258:	learn: 0.0229243	total: 116ms	remaining: 331ms
259:	learn: 0.0228370	total: 116ms	remaining: 330ms
260:	learn: 0.0227207	total: 116ms	remaining: 329ms
261:	learn: 0.0226208	total: 116ms	remaining: 328ms
262:	learn: 0.0225107	total: 117ms	remaining: 327ms
263:	learn: 0.0223456	total: 117ms	remaining: 325ms
264:	learn: 0.0222681	total: 117ms	remaining: 324ms
265:	learn: 0.0221768	total: 117ms	remaining: 323ms
266:	learn: 0.0220623	total: 117ms	remaining: 322ms
267:	learn: 0.0219582	total: 117ms	remaining: 321ms
268:	learn: 0.0218558	total: 118ms	remaining: 320ms
269:	learn: 0.0217457	total: 118ms	remaining: 319ms
270:	learn: 0.0215949	total: 118ms	remaining: 317ms
271:	learn: 0.0215269	total: 118ms	remaining: 316ms
272:	learn: 0.0213798	total: 118ms	remaining: 315ms
273:	learn: 0.0212846	total: 119ms	remaining: 314ms
274:	learn: 0.0211900	total: 119ms	remaining: 313ms
275:	learn: 0.0210868	total: 119ms	remaining: 312ms
276:	learn: 0.0209924	total: 119ms	remaining: 311ms
277:	learn: 0.0208711	total: 119ms	remaining: 310ms
278:	learn: 0.0207756	total: 120ms	remaining: 309ms
279:	learn: 0.0206969	total: 120ms	remaining: 308ms
280:	learn: 0.0206053	total: 120ms	remaining: 307ms
281:	learn: 0.0205458	total: 120ms	remaining: 306ms
282:	learn: 0.0204826	total: 120ms	remaining: 305ms
283:	learn: 0.0204046	total: 121ms	remaining: 304ms
284:	learn: 0.0203229	total: 121ms	remaining: 303ms
285:	learn: 0.0202420	total: 121ms	remaining: 302ms
286:	learn: 0.0201551	total: 121ms	remaining: 301ms
287:	learn: 0.0200826	total: 121ms	remaining: 300ms
288:	learn: 0.0200171	total: 121ms	remaining: 299ms
289:	learn: 0.0199358	total: 122ms	remaining: 298ms
290:	learn: 0.0198112	total: 122ms	remaining: 297ms
291:	learn: 0.0197466	total: 122ms	remaining: 296ms
292:	learn: 0.0196853	total: 122ms	remaining: 295ms
293:	learn: 0.0195570	total: 122ms	remaining: 294ms
294:	learn: 0.0194812	total: 123ms	remaining: 293ms
295:	learn: 0.0193886	total: 123ms	remaining: 292ms
296:	learn: 0.0193381	total: 123ms	remaining: 291ms
297:	learn: 0.0192563	total: 123ms	remaining: 290ms
298:	learn: 0.0191666	total: 123ms	remaining: 289ms
299:	learn: 0.0191058	total: 123ms	remaining: 288ms
300:	learn: 0.0190393	total: 124ms	remaining: 287ms
301:	learn: 0.0189273	total: 124ms	remaining: 287ms
302:	learn: 0.0188538	total: 124ms	remaining: 286ms
303:	learn: 0.0187978	total: 124ms	remaining: 285ms
304:	learn: 0.0187382	total: 124ms	remaining: 284ms
305:	learn: 0.0186276	total: 125ms	remaining: 283ms
306:	learn: 0.0185326	total: 125ms	remaining: 282ms
307:	learn: 0.0184674	total: 125ms	remaining: 281ms
308:	learn: 0.0183880	total: 125ms	remaining: 280ms
309:	learn: 0.0183310	total: 125ms	remaining: 279ms
310:	learn: 0.0182737	total: 125ms	remaining: 278ms
311:	learn: 0.0182176	total: 126ms	remaining: 277ms
312:	learn: 0.0181649	total: 126ms	remaining: 276ms
313:	learn: 0.0180929	total: 126ms	remaining: 275ms
314:	learn: 0.0180331	total: 126ms	remaining: 275ms
315:	learn: 0.0179580	total: 126ms	remaining: 274ms
316:	learn: 0.0178742	total: 127ms	remaining: 273ms
317:	learn: 0.0178194	total: 127ms	remaining: 272ms
318:	learn: 0.0177622	total: 127ms	remaining: 271ms
319:	learn: 0.0176914	total: 127ms	remaining: 270ms
320:	learn: 0.0176231	total: 127ms	remaining: 269ms
321:	learn: 0.0175757	total: 128ms	remaining: 269ms
322:	learn: 0.0175087	total: 128ms	remaining: 268ms
323:	learn: 0.0174590	total: 128ms	remaining: 267ms
324:	learn: 0.0174126	total: 128ms	remaining: 266ms
325:	learn: 0.0173603	total: 128ms	remaining: 265ms
326:	learn: 0.0173017	total: 128ms	remaining: 264ms
327:	learn: 0.0172008	total: 129ms	remaining: 263ms
328:	learn: 0.0171340	total: 129ms	remaining: 263ms
329:	learn: 0.0170463	total: 129ms	remaining: 262ms
330:	learn: 0.0169844	total: 129ms	remaining: 261ms
331:	learn: 0.0169133	total: 129ms	remaining: 260ms
332:	learn: 0.0168653	total: 129ms	remaining: 259ms
333:	learn: 0.0168235	total: 130ms	remaining: 259ms
334:	learn: 0.0167564	total: 130ms	remaining: 258ms
335:	learn: 0.0166950	total: 130ms	remaining: 257ms
336:	learn: 0.0166460	total: 130ms	remaining: 256ms
337:	learn: 0.0165923	total: 130ms	remaining: 255ms
338:	learn: 0.0165509	total: 130ms	remaining: 254ms
339:	learn: 0.0164827	total: 131ms	remaining: 254ms
340:	learn: 0.0164028	total: 131ms	remaining: 253ms
341:	learn: 0.0163505	total: 131ms	remaining: 252ms
342:	learn: 0.0163201	total: 131ms	remaining: 251ms
343:	learn: 0.0162603	total: 131ms	remaining: 251ms
344:	learn: 0.0162017	total: 132ms	remaining: 250ms
345:	learn: 0.0161496	total: 132ms	remaining: 249ms
346:	learn: 0.0160849	total: 132ms	remaining: 248ms
347:	learn: 0.0160186	total: 132ms	remaining: 247ms
348:	learn: 0.0159363	total: 132ms	remaining: 247ms
349:	learn: 0.0158690	total: 132ms	remaining: 246ms
350:	learn: 0.0158133	total: 133ms	remaining: 245ms
351:	learn: 0.0157619	total: 133ms	remaining: 245ms
352:	learn: 0.0157174	total: 133ms	remaining: 244ms
353:	learn: 0.0156706	total: 133ms	remaining: 243ms
354:	learn: 0.0156088	total: 133ms	remaining: 242ms
355:	learn: 0.0155542	total: 134ms	remaining: 242ms
356:	learn: 0.0155123	total: 134ms	remaining: 241ms
357:	learn: 0.0154649	total: 134ms	remaining: 240ms
358:	learn: 0.0154111	total: 134ms	remaining: 239ms
359:	learn: 0.0153562	total: 134ms	remaining: 239ms
360:	learn: 0.0153124	total: 134ms	remaining: 238ms
361:	learn: 0.0152587	total: 135ms	remaining: 237ms
362:	learn: 0.0151764	total: 135ms	remaining: 237ms
363:	learn: 0.0151188	total: 135ms	remaining: 236ms
364:	learn: 0.0150739	total: 135ms	remaining: 235ms
365:	learn: 0.0150277	total: 135ms	remaining: 234ms
366:	learn: 0.0149832	total: 135ms	remaining: 234ms
367:	learn: 0.0149315	total: 136ms	remaining: 233ms
368:	learn: 0.0148692	total: 136ms	remaining: 232ms
369:	learn: 0.0148123	total: 136ms	remaining: 231ms
370:	learn: 0.0147799	total: 136ms	remaining: 231ms
371:	learn: 0.0147076	total: 136ms	remaining: 230ms
372:	learn: 0.0146752	total: 136ms	remaining: 229ms
373:	learn: 0.0146296	total: 137ms	remaining: 229ms
374:	learn: 0.0145802	total: 137ms	remaining: 228ms
375:	learn: 0.0145357	total: 137ms	remaining: 227ms
376:	learn: 0.0144772	total: 137ms	remaining: 227ms
377:	learn: 0.0144246	total: 137ms	remaining: 226ms
378:	learn: 0.0143883	total: 137ms	remaining: 225ms
379:	learn: 0.0143452	total: 138ms	remaining: 225ms
380:	learn: 0.0143030	total: 138ms	remaining: 224ms
381:	learn: 0.0142592	total: 138ms	remaining: 223ms
382:	learn: 0.0142138	total: 138ms	remaining: 223ms

In [19]:
model5 = LGBMClassifier()
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))
print("confusion_matrix:",confusion_matrix(y_test,y_pred5))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000155 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 91
[LightGBM] [Info] Number of data points in the train set: 120, number of used features: 4
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.073920
[LightGBM] [Info] Start training from score -1.123930
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf