In [2]:
import numpy as np 
import pandas as pd

from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df = pd.read_csv('medical.csv')

In [4]:
df.shape

(110527, 14)

In [5]:
df.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [7]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [9]:
df['No-show'].unique()

array(['No', 'Yes'], dtype=object)

In [8]:
df.drop(['AppointmentID','PatientId'],axis=1,inplace=True)

In [10]:
df['No-show']=df['No-show'].map({"Yes":1,"No":0})

In [11]:
df["Gender"] = df["Gender"].map({"F":0, "M":1})

In [12]:
df["ScheduledDay"] = pd.to_datetime(df["ScheduledDay"])
df["AppointmentDay"] = pd.to_datetime(df["AppointmentDay"])

In [13]:
df["waiting_days"] = (df["AppointmentDay"] - df["ScheduledDay"]).dt.days

In [14]:
df = df.drop(["ScheduledDay","AppointmentDay"], axis=1)

In [15]:
df = pd.get_dummies(df, columns=["Neighbourhood"], drop_first=True)

In [16]:
X= df.drop('No-show',axis=1)
y=df['No-show']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
model1 = AdaBoostClassifier(n_estimators=200,random_state=42)
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred1))
print('classification_report:',classification_report(y_test,y_pred1))
print('confusion_matrix:',confusion_matrix(y_test,y_pred1))

accuracy_Score: 0.7994209716818963
classification_report:               precision    recall  f1-score   support

           0       0.80      1.00      0.89     17669
           1       0.64      0.00      0.00      4437

    accuracy                           0.80     22106
   macro avg       0.72      0.50      0.45     22106
weighted avg       0.77      0.80      0.71     22106

confusion_matrix: [[17665     4]
 [ 4430     7]]

In [22]:
model2 = GradientBoostingClassifier()
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred2))
print('classification_report:',classification_report(y_test,y_pred2))
print('confusion_matrix:',confusion_matrix(y_test,y_pred2))

accuracy_Score: 0.7993757350945445
classification_report:               precision    recall  f1-score   support

           0       0.80      1.00      0.89     17669
           1       0.53      0.00      0.01      4437

    accuracy                           0.80     22106
   macro avg       0.66      0.50      0.45     22106
weighted avg       0.74      0.80      0.71     22106

confusion_matrix: [[17651    18]
 [ 4417    20]]

In [23]:
model3 = XGBClassifier()
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred3))
print('classification_report:',classification_report(y_test,y_pred3))
print('confusion_matrix:',confusion_matrix(y_test,y_pred3))

accuracy_Score: 0.8002352302542296
classification_report:               precision    recall  f1-score   support

           0       0.81      0.99      0.89     17669
           1       0.52      0.06      0.11      4437

    accuracy                           0.80     22106
   macro avg       0.66      0.52      0.50     22106
weighted avg       0.75      0.80      0.73     22106

confusion_matrix: [[17416   253]
 [ 4163   274]]

In [24]:
model4 = LGBMClassifier()
model4.fit(X_train,y_train)
y_pred4 = model4.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred4))
print('classification_report:',classification_report(y_test,y_pred4))
print('confusion_matrix:',confusion_matrix(y_test,y_pred4))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 17882, number of negative: 70539
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001906 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 387
[LightGBM] [Info] Number of data points in the train set: 88421, number of used features: 86
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.202237 -> initscore=-1.372371
[LightGBM] [Info] Start training from score -1.372371
accuracy_Score: 0.8001447570795259
classification_report:               precision    recall  f1-score   support

           0       0.80      1.00      0.89     17669
           1       0.56      0.02      0.04      4437

    accuracy                           0.80     22106
   macro avg       0.68      0.51      0.46     22106
weighted avg       0.75      0.80      0.72     22106

confusion_matrix: [[17595    74]
 [ 4344    93]]

In [26]:
model5 = CatBoostClassifier()
model5.fit(X_train,y_train)
y_pred5 = model5.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred5))
print('classification_report:',classification_report(y_test,y_pred5))
print('confusion_matrix:',confusion_matrix(y_test,y_pred5))

Learning rate set to 0.069841
0:	learn: 0.6515559	total: 65.9ms	remaining: 1m 5s
1:	learn: 0.6171207	total: 73.2ms	remaining: 36.5s
2:	learn: 0.5888536	total: 80.3ms	remaining: 26.7s
3:	learn: 0.5672968	total: 87ms	remaining: 21.7s
4:	learn: 0.5502420	total: 93.4ms	remaining: 18.6s
5:	learn: 0.5346606	total: 100ms	remaining: 16.6s
6:	learn: 0.5228850	total: 106ms	remaining: 15s
7:	learn: 0.5102800	total: 112ms	remaining: 13.9s
8:	learn: 0.5017604	total: 117ms	remaining: 12.9s
9:	learn: 0.4928356	total: 123ms	remaining: 12.1s
10:	learn: 0.4853788	total: 128ms	remaining: 11.5s
11:	learn: 0.4806844	total: 134ms	remaining: 11s
12:	learn: 0.4768524	total: 140ms	remaining: 10.6s
13:	learn: 0.4732906	total: 146ms	remaining: 10.3s
14:	learn: 0.4690904	total: 152ms	remaining: 9.99s
15:	learn: 0.4655108	total: 158ms	remaining: 9.7s
16:	learn: 0.4634416	total: 163ms	remaining: 9.43s
17:	learn: 0.4614713	total: 169ms	remaining: 9.22s
18:	learn: 0.4589816	total: 175ms	remaining: 9.03s
19:	learn: 0.4577725	total: 181ms	remaining: 8.86s
20:	learn: 0.4557914	total: 187ms	remaining: 8.71s
21:	learn: 0.4546622	total: 193ms	remaining: 8.57s
22:	learn: 0.4538622	total: 198ms	remaining: 8.42s
23:	learn: 0.4524258	total: 204ms	remaining: 8.31s
24:	learn: 0.4512974	total: 210ms	remaining: 8.2s
25:	learn: 0.4507244	total: 216ms	remaining: 8.1s
26:	learn: 0.4498172	total: 223ms	remaining: 8.02s
27:	learn: 0.4489791	total: 229ms	remaining: 7.93s
28:	learn: 0.4486107	total: 234ms	remaining: 7.84s
29:	learn: 0.4479969	total: 240ms	remaining: 7.76s
30:	learn: 0.4476258	total: 246ms	remaining: 7.68s
31:	learn: 0.4473515	total: 252ms	remaining: 7.61s
32:	learn: 0.4470569	total: 257ms	remaining: 7.54s
33:	learn: 0.4465177	total: 264ms	remaining: 7.49s
34:	learn: 0.4461112	total: 269ms	remaining: 7.43s
35:	learn: 0.4457434	total: 275ms	remaining: 7.37s
36:	learn: 0.4454190	total: 281ms	remaining: 7.31s
37:	learn: 0.4450728	total: 287ms	remaining: 7.26s
38:	learn: 0.4449392	total: 293ms	remaining: 7.21s
39:	learn: 0.4448216	total: 299ms	remaining: 7.17s
40:	learn: 0.4445821	total: 305ms	remaining: 7.13s
41:	learn: 0.4443263	total: 311ms	remaining: 7.08s
42:	learn: 0.4441789	total: 316ms	remaining: 7.04s
43:	learn: 0.4440653	total: 322ms	remaining: 7s
44:	learn: 0.4439435	total: 328ms	remaining: 6.96s
45:	learn: 0.4438666	total: 334ms	remaining: 6.92s
46:	learn: 0.4437218	total: 339ms	remaining: 6.88s
47:	learn: 0.4436306	total: 345ms	remaining: 6.84s
48:	learn: 0.4434755	total: 350ms	remaining: 6.8s
49:	learn: 0.4432617	total: 357ms	remaining: 6.78s
50:	learn: 0.4430797	total: 362ms	remaining: 6.74s
51:	learn: 0.4428482	total: 368ms	remaining: 6.71s
52:	learn: 0.4426211	total: 374ms	remaining: 6.68s
53:	learn: 0.4425260	total: 380ms	remaining: 6.66s
54:	learn: 0.4424602	total: 386ms	remaining: 6.62s
55:	learn: 0.4423174	total: 391ms	remaining: 6.6s
56:	learn: 0.4422485	total: 398ms	remaining: 6.58s
57:	learn: 0.4421722	total: 404ms	remaining: 6.56s
58:	learn: 0.4420989	total: 410ms	remaining: 6.54s
59:	learn: 0.4420362	total: 416ms	remaining: 6.52s
60:	learn: 0.4419829	total: 422ms	remaining: 6.49s
61:	learn: 0.4419223	total: 427ms	remaining: 6.47s
62:	learn: 0.4418598	total: 433ms	remaining: 6.45s
63:	learn: 0.4417819	total: 439ms	remaining: 6.42s
64:	learn: 0.4417215	total: 445ms	remaining: 6.4s
65:	learn: 0.4416276	total: 451ms	remaining: 6.38s
66:	learn: 0.4415684	total: 457ms	remaining: 6.37s
67:	learn: 0.4415001	total: 463ms	remaining: 6.35s
68:	learn: 0.4414374	total: 469ms	remaining: 6.32s
69:	learn: 0.4413467	total: 474ms	remaining: 6.3s
70:	learn: 0.4412945	total: 480ms	remaining: 6.28s
71:	learn: 0.4412661	total: 486ms	remaining: 6.26s
72:	learn: 0.4411964	total: 492ms	remaining: 6.25s
73:	learn: 0.4411394	total: 498ms	remaining: 6.23s
74:	learn: 0.4411011	total: 504ms	remaining: 6.21s
75:	learn: 0.4410606	total: 510ms	remaining: 6.2s
76:	learn: 0.4410239	total: 516ms	remaining: 6.18s
77:	learn: 0.4409950	total: 522ms	remaining: 6.17s
78:	learn: 0.4409495	total: 528ms	remaining: 6.15s
79:	learn: 0.4408460	total: 534ms	remaining: 6.14s
80:	learn: 0.4408017	total: 540ms	remaining: 6.13s
81:	learn: 0.4407495	total: 546ms	remaining: 6.11s
82:	learn: 0.4407054	total: 552ms	remaining: 6.1s
83:	learn: 0.4406664	total: 558ms	remaining: 6.09s
84:	learn: 0.4405888	total: 564ms	remaining: 6.07s
85:	learn: 0.4405412	total: 570ms	remaining: 6.06s
86:	learn: 0.4404750	total: 576ms	remaining: 6.05s
87:	learn: 0.4404315	total: 583ms	remaining: 6.04s
88:	learn: 0.4403523	total: 589ms	remaining: 6.03s
89:	learn: 0.4403200	total: 595ms	remaining: 6.01s
90:	learn: 0.4402777	total: 601ms	remaining: 6s
91:	learn: 0.4402359	total: 607ms	remaining: 5.99s
92:	learn: 0.4401864	total: 613ms	remaining: 5.98s
93:	learn: 0.4401092	total: 619ms	remaining: 5.97s
94:	learn: 0.4400827	total: 625ms	remaining: 5.96s
95:	learn: 0.4400112	total: 631ms	remaining: 5.94s
96:	learn: 0.4399499	total: 637ms	remaining: 5.93s
97:	learn: 0.4398806	total: 643ms	remaining: 5.92s
98:	learn: 0.4398046	total: 649ms	remaining: 5.91s
99:	learn: 0.4397816	total: 655ms	remaining: 5.9s
100:	learn: 0.4397335	total: 661ms	remaining: 5.88s
101:	learn: 0.4396832	total: 668ms	remaining: 5.88s
102:	learn: 0.4396169	total: 674ms	remaining: 5.87s
103:	learn: 0.4396064	total: 680ms	remaining: 5.86s
104:	learn: 0.4395667	total: 686ms	remaining: 5.85s
105:	learn: 0.4395340	total: 692ms	remaining: 5.83s
106:	learn: 0.4394593	total: 698ms	remaining: 5.82s
107:	learn: 0.4394021	total: 703ms	remaining: 5.81s
108:	learn: 0.4393322	total: 710ms	remaining: 5.8s
109:	learn: 0.4392986	total: 715ms	remaining: 5.79s
110:	learn: 0.4392449	total: 721ms	remaining: 5.78s
111:	learn: 0.4392158	total: 727ms	remaining: 5.76s
112:	learn: 0.4391950	total: 733ms	remaining: 5.76s
113:	learn: 0.4391405	total: 739ms	remaining: 5.75s
114:	learn: 0.4390981	total: 745ms	remaining: 5.74s
115:	learn: 0.4390481	total: 751ms	remaining: 5.72s
116:	learn: 0.4389992	total: 757ms	remaining: 5.71s
117:	learn: 0.4389727	total: 763ms	remaining: 5.7s
118:	learn: 0.4389003	total: 769ms	remaining: 5.7s
119:	learn: 0.4388801	total: 775ms	remaining: 5.69s
120:	learn: 0.4388107	total: 781ms	remaining: 5.68s
121:	learn: 0.4387739	total: 787ms	remaining: 5.66s
122:	learn: 0.4387388	total: 793ms	remaining: 5.65s
123:	learn: 0.4386937	total: 799ms	remaining: 5.64s
124:	learn: 0.4386677	total: 805ms	remaining: 5.63s
125:	learn: 0.4386242	total: 812ms	remaining: 5.63s
126:	learn: 0.4385800	total: 818ms	remaining: 5.62s
127:	learn: 0.4385597	total: 824ms	remaining: 5.61s
128:	learn: 0.4385195	total: 830ms	remaining: 5.6s
129:	learn: 0.4384833	total: 836ms	remaining: 5.59s
130:	learn: 0.4384385	total: 841ms	remaining: 5.58s
131:	learn: 0.4384101	total: 847ms	remaining: 5.57s
132:	learn: 0.4383725	total: 853ms	remaining: 5.56s
133:	learn: 0.4383388	total: 859ms	remaining: 5.55s
134:	learn: 0.4383144	total: 865ms	remaining: 5.54s
135:	learn: 0.4382747	total: 871ms	remaining: 5.53s
136:	learn: 0.4381880	total: 877ms	remaining: 5.52s
137:	learn: 0.4381667	total: 882ms	remaining: 5.51s
138:	learn: 0.4381188	total: 888ms	remaining: 5.5s
139:	learn: 0.4380848	total: 894ms	remaining: 5.49s
140:	learn: 0.4380322	total: 900ms	remaining: 5.48s
141:	learn: 0.4379985	total: 906ms	remaining: 5.47s
142:	learn: 0.4379651	total: 912ms	remaining: 5.47s
143:	learn: 0.4379480	total: 918ms	remaining: 5.46s
144:	learn: 0.4378930	total: 923ms	remaining: 5.45s
145:	learn: 0.4378592	total: 930ms	remaining: 5.44s
146:	learn: 0.4378136	total: 936ms	remaining: 5.43s
147:	learn: 0.4377981	total: 941ms	remaining: 5.42s
148:	learn: 0.4377692	total: 947ms	remaining: 5.41s
149:	learn: 0.4377157	total: 953ms	remaining: 5.4s
150:	learn: 0.4376675	total: 959ms	remaining: 5.39s
151:	learn: 0.4376274	total: 965ms	remaining: 5.38s
152:	learn: 0.4376031	total: 971ms	remaining: 5.38s
153:	learn: 0.4375765	total: 977ms	remaining: 5.37s
154:	learn: 0.4375295	total: 983ms	remaining: 5.36s
155:	learn: 0.4374773	total: 989ms	remaining: 5.35s
156:	learn: 0.4374268	total: 996ms	remaining: 5.34s
157:	learn: 0.4373887	total: 1s	remaining: 5.33s
158:	learn: 0.4373541	total: 1.01s	remaining: 5.33s
159:	learn: 0.4373074	total: 1.01s	remaining: 5.33s
160:	learn: 0.4372585	total: 1.02s	remaining: 5.32s
161:	learn: 0.4372006	total: 1.03s	remaining: 5.31s
162:	learn: 0.4371507	total: 1.03s	remaining: 5.31s
163:	learn: 0.4371373	total: 1.04s	remaining: 5.31s
164:	learn: 0.4371019	total: 1.05s	remaining: 5.3s
165:	learn: 0.4370590	total: 1.05s	remaining: 5.29s
166:	learn: 0.4369814	total: 1.06s	remaining: 5.29s
167:	learn: 0.4369317	total: 1.07s	remaining: 5.28s
168:	learn: 0.4368747	total: 1.07s	remaining: 5.27s
169:	learn: 0.4368229	total: 1.08s	remaining: 5.27s
170:	learn: 0.4367786	total: 1.08s	remaining: 5.26s
171:	learn: 0.4367204	total: 1.09s	remaining: 5.25s
172:	learn: 0.4366784	total: 1.1s	remaining: 5.25s
173:	learn: 0.4366467	total: 1.1s	remaining: 5.24s
174:	learn: 0.4366024	total: 1.11s	remaining: 5.23s
175:	learn: 0.4365707	total: 1.11s	remaining: 5.22s
176:	learn: 0.4365194	total: 1.12s	remaining: 5.21s
177:	learn: 0.4364878	total: 1.13s	remaining: 5.21s
178:	learn: 0.4364198	total: 1.13s	remaining: 5.2s
179:	learn: 0.4363911	total: 1.14s	remaining: 5.19s
180:	learn: 0.4363371	total: 1.15s	remaining: 5.18s
181:	learn: 0.4363039	total: 1.15s	remaining: 5.17s
182:	learn: 0.4362486	total: 1.16s	remaining: 5.17s
183:	learn: 0.4361996	total: 1.16s	remaining: 5.16s
184:	learn: 0.4361539	total: 1.17s	remaining: 5.15s
185:	learn: 0.4361192	total: 1.18s	remaining: 5.14s
186:	learn: 0.4360084	total: 1.18s	remaining: 5.14s
187:	learn: 0.4359149	total: 1.19s	remaining: 5.13s
188:	learn: 0.4358468	total: 1.19s	remaining: 5.12s
189:	learn: 0.4357632	total: 1.2s	remaining: 5.11s
190:	learn: 0.4356825	total: 1.21s	remaining: 5.11s
191:	learn: 0.4356344	total: 1.21s	remaining: 5.1s
192:	learn: 0.4355920	total: 1.22s	remaining: 5.09s
193:	learn: 0.4355515	total: 1.22s	remaining: 5.09s
194:	learn: 0.4355082	total: 1.23s	remaining: 5.08s
195:	learn: 0.4354229	total: 1.24s	remaining: 5.07s
196:	learn: 0.4353578	total: 1.24s	remaining: 5.07s
197:	learn: 0.4353079	total: 1.25s	remaining: 5.06s
198:	learn: 0.4352610	total: 1.25s	remaining: 5.05s
199:	learn: 0.4352416	total: 1.26s	remaining: 5.04s
200:	learn: 0.4351724	total: 1.27s	remaining: 5.04s
201:	learn: 0.4351253	total: 1.27s	remaining: 5.03s
202:	learn: 0.4350364	total: 1.28s	remaining: 5.02s
203:	learn: 0.4349637	total: 1.28s	remaining: 5.01s
204:	learn: 0.4348975	total: 1.29s	remaining: 5s
205:	learn: 0.4348660	total: 1.3s	remaining: 5s
206:	learn: 0.4348187	total: 1.3s	remaining: 4.99s
207:	learn: 0.4347822	total: 1.31s	remaining: 4.98s
208:	learn: 0.4347417	total: 1.31s	remaining: 4.97s
209:	learn: 0.4346737	total: 1.32s	remaining: 4.97s
210:	learn: 0.4346311	total: 1.33s	remaining: 4.96s
211:	learn: 0.4345816	total: 1.33s	remaining: 4.95s
212:	learn: 0.4345276	total: 1.34s	remaining: 4.95s
213:	learn: 0.4344927	total: 1.34s	remaining: 4.94s
214:	learn: 0.4344502	total: 1.35s	remaining: 4.93s
215:	learn: 0.4344050	total: 1.36s	remaining: 4.92s
216:	learn: 0.4343385	total: 1.36s	remaining: 4.92s
217:	learn: 0.4342609	total: 1.37s	remaining: 4.91s
218:	learn: 0.4341954	total: 1.38s	remaining: 4.9s
219:	learn: 0.4341394	total: 1.38s	remaining: 4.89s
220:	learn: 0.4340824	total: 1.39s	remaining: 4.89s
221:	learn: 0.4340232	total: 1.39s	remaining: 4.88s
222:	learn: 0.4339771	total: 1.4s	remaining: 4.87s
223:	learn: 0.4339290	total: 1.4s	remaining: 4.87s
224:	learn: 0.4338659	total: 1.41s	remaining: 4.86s
225:	learn: 0.4338008	total: 1.42s	remaining: 4.85s
226:	learn: 0.4337813	total: 1.42s	remaining: 4.84s
227:	learn: 0.4337309	total: 1.43s	remaining: 4.84s
228:	learn: 0.4336864	total: 1.43s	remaining: 4.83s
229:	learn: 0.4336352	total: 1.44s	remaining: 4.82s
230:	learn: 0.4335869	total: 1.45s	remaining: 4.82s
231:	learn: 0.4335416	total: 1.45s	remaining: 4.81s
232:	learn: 0.4334933	total: 1.46s	remaining: 4.8s
233:	learn: 0.4334262	total: 1.46s	remaining: 4.79s
234:	learn: 0.4333833	total: 1.47s	remaining: 4.79s
235:	learn: 0.4333450	total: 1.48s	remaining: 4.78s
236:	learn: 0.4332977	total: 1.48s	remaining: 4.77s
237:	learn: 0.4332535	total: 1.49s	remaining: 4.76s
238:	learn: 0.4332291	total: 1.49s	remaining: 4.76s
239:	learn: 0.4331834	total: 1.5s	remaining: 4.75s
240:	learn: 0.4331667	total: 1.5s	remaining: 4.74s
241:	learn: 0.4331223	total: 1.51s	remaining: 4.73s
242:	learn: 0.4330694	total: 1.52s	remaining: 4.73s
243:	learn: 0.4330252	total: 1.52s	remaining: 4.72s
244:	learn: 0.4329779	total: 1.53s	remaining: 4.71s
245:	learn: 0.4329377	total: 1.53s	remaining: 4.71s
246:	learn: 0.4328796	total: 1.54s	remaining: 4.7s
247:	learn: 0.4328436	total: 1.55s	remaining: 4.69s
248:	learn: 0.4328019	total: 1.55s	remaining: 4.68s
249:	learn: 0.4327624	total: 1.56s	remaining: 4.68s
250:	learn: 0.4327222	total: 1.56s	remaining: 4.67s
251:	learn: 0.4326844	total: 1.57s	remaining: 4.66s
252:	learn: 0.4326447	total: 1.58s	remaining: 4.66s
253:	learn: 0.4325962	total: 1.58s	remaining: 4.65s
254:	learn: 0.4325354	total: 1.59s	remaining: 4.64s
255:	learn: 0.4324886	total: 1.59s	remaining: 4.64s
256:	learn: 0.4324432	total: 1.6s	remaining: 4.63s
257:	learn: 0.4324048	total: 1.61s	remaining: 4.62s
258:	learn: 0.4323728	total: 1.61s	remaining: 4.62s
259:	learn: 0.4323222	total: 1.62s	remaining: 4.61s
260:	learn: 0.4322691	total: 1.63s	remaining: 4.6s
261:	learn: 0.4322313	total: 1.63s	remaining: 4.59s
262:	learn: 0.4321952	total: 1.66s	remaining: 4.64s
263:	learn: 0.4321477	total: 1.67s	remaining: 4.64s
264:	learn: 0.4321006	total: 1.67s	remaining: 4.64s
265:	learn: 0.4320684	total: 1.68s	remaining: 4.63s
266:	learn: 0.4320522	total: 1.68s	remaining: 4.62s
267:	learn: 0.4320028	total: 1.69s	remaining: 4.62s
268:	learn: 0.4319839	total: 1.7s	remaining: 4.61s
269:	learn: 0.4319458	total: 1.7s	remaining: 4.6s
270:	learn: 0.4318923	total: 1.71s	remaining: 4.59s
271:	learn: 0.4318554	total: 1.71s	remaining: 4.59s
272:	learn: 0.4317990	total: 1.72s	remaining: 4.58s
273:	learn: 0.4317447	total: 1.73s	remaining: 4.57s
274:	learn: 0.4316892	total: 1.73s	remaining: 4.57s
275:	learn: 0.4316332	total: 1.74s	remaining: 4.56s
276:	learn: 0.4315922	total: 1.74s	remaining: 4.55s
277:	learn: 0.4315526	total: 1.75s	remaining: 4.54s
278:	learn: 0.4315379	total: 1.75s	remaining: 4.54s
279:	learn: 0.4314887	total: 1.76s	remaining: 4.53s
280:	learn: 0.4314492	total: 1.77s	remaining: 4.52s
281:	learn: 0.4313904	total: 1.77s	remaining: 4.52s
282:	learn: 0.4313454	total: 1.78s	remaining: 4.51s
283:	learn: 0.4313069	total: 1.78s	remaining: 4.5s
284:	learn: 0.4312679	total: 1.79s	remaining: 4.5s
285:	learn: 0.4312264	total: 1.8s	remaining: 4.49s
286:	learn: 0.4311850	total: 1.8s	remaining: 4.48s
287:	learn: 0.4311503	total: 1.81s	remaining: 4.47s
288:	learn: 0.4311053	total: 1.82s	remaining: 4.47s
289:	learn: 0.4310573	total: 1.82s	remaining: 4.46s
290:	learn: 0.4310260	total: 1.83s	remaining: 4.45s
291:	learn: 0.4309527	total: 1.83s	remaining: 4.45s
292:	learn: 0.4309165	total: 1.84s	remaining: 4.44s
293:	learn: 0.4308808	total: 1.85s	remaining: 4.44s
294:	learn: 0.4308319	total: 1.85s	remaining: 4.43s
295:	learn: 0.4307947	total: 1.86s	remaining: 4.42s
296:	learn: 0.4307602	total: 1.87s	remaining: 4.42s
297:	learn: 0.4307074	total: 1.87s	remaining: 4.41s
298:	learn: 0.4306566	total: 1.88s	remaining: 4.4s
299:	learn: 0.4306224	total: 1.88s	remaining: 4.4s
300:	learn: 0.4305881	total: 1.89s	remaining: 4.39s
301:	learn: 0.4305375	total: 1.9s	remaining: 4.38s
302:	learn: 0.4304934	total: 1.9s	remaining: 4.38s
303:	learn: 0.4304784	total: 1.91s	remaining: 4.37s
304:	learn: 0.4304312	total: 1.91s	remaining: 4.36s
305:	learn: 0.4303999	total: 1.92s	remaining: 4.36s
306:	learn: 0.4303649	total: 1.93s	remaining: 4.35s
307:	learn: 0.4303004	total: 1.93s	remaining: 4.34s
308:	learn: 0.4302646	total: 1.94s	remaining: 4.33s
309:	learn: 0.4302076	total: 1.94s	remaining: 4.33s
310:	learn: 0.4301720	total: 1.95s	remaining: 4.32s
311:	learn: 0.4301421	total: 1.96s	remaining: 4.31s
312:	learn: 0.4301022	total: 1.96s	remaining: 4.31s
313:	learn: 0.4300668	total: 1.97s	remaining: 4.3s
314:	learn: 0.4300484	total: 1.97s	remaining: 4.29s
315:	learn: 0.4299970	total: 1.98s	remaining: 4.29s
316:	learn: 0.4299630	total: 1.99s	remaining: 4.28s
317:	learn: 0.4299340	total: 1.99s	remaining: 4.27s
318:	learn: 0.4298991	total: 2s	remaining: 4.26s
319:	learn: 0.4298668	total: 2s	remaining: 4.26s
320:	learn: 0.4298315	total: 2.01s	remaining: 4.25s
321:	learn: 0.4297935	total: 2.01s	remaining: 4.24s
322:	learn: 0.4297552	total: 2.02s	remaining: 4.23s
323:	learn: 0.4297279	total: 2.03s	remaining: 4.23s
324:	learn: 0.4296807	total: 2.03s	remaining: 4.22s
325:	learn: 0.4296466	total: 2.04s	remaining: 4.21s
326:	learn: 0.4296180	total: 2.04s	remaining: 4.21s
327:	learn: 0.4295717	total: 2.05s	remaining: 4.2s
328:	learn: 0.4295320	total: 2.06s	remaining: 4.19s
329:	learn: 0.4295074	total: 2.06s	remaining: 4.19s
330:	learn: 0.4294630	total: 2.07s	remaining: 4.18s
331:	learn: 0.4294271	total: 2.07s	remaining: 4.17s
332:	learn: 0.4293881	total: 2.08s	remaining: 4.16s
333:	learn: 0.4293588	total: 2.08s	remaining: 4.16s
334:	learn: 0.4293301	total: 2.09s	remaining: 4.15s
335:	learn: 0.4293087	total: 2.1s	remaining: 4.14s
336:	learn: 0.4292753	total: 2.1s	remaining: 4.13s
337:	learn: 0.4292568	total: 2.11s	remaining: 4.13s
338:	learn: 0.4292201	total: 2.11s	remaining: 4.12s
339:	learn: 0.4291925	total: 2.12s	remaining: 4.11s
340:	learn: 0.4291620	total: 2.13s	remaining: 4.11s
341:	learn: 0.4291132	total: 2.13s	remaining: 4.1s
342:	learn: 0.4290580	total: 2.14s	remaining: 4.09s
343:	learn: 0.4290372	total: 2.14s	remaining: 4.08s
344:	learn: 0.4290125	total: 2.15s	remaining: 4.08s
345:	learn: 0.4289693	total: 2.15s	remaining: 4.07s
346:	learn: 0.4289284	total: 2.16s	remaining: 4.06s
347:	learn: 0.4288925	total: 2.17s	remaining: 4.06s
348:	learn: 0.4288570	total: 2.17s	remaining: 4.05s
349:	learn: 0.4288134	total: 2.18s	remaining: 4.04s
350:	learn: 0.4287811	total: 2.18s	remaining: 4.04s
351:	learn: 0.4287249	total: 2.19s	remaining: 4.03s
352:	learn: 0.4286989	total: 2.19s	remaining: 4.02s
353:	learn: 0.4286541	total: 2.2s	remaining: 4.01s
354:	learn: 0.4286432	total: 2.21s	remaining: 4.01s
355:	learn: 0.4286157	total: 2.21s	remaining: 4s
356:	learn: 0.4285726	total: 2.22s	remaining: 3.99s
357:	learn: 0.4285429	total: 2.22s	remaining: 3.99s
358:	learn: 0.4285229	total: 2.23s	remaining: 3.98s
359:	learn: 0.4284883	total: 2.23s	remaining: 3.97s
360:	learn: 0.4284444	total: 2.24s	remaining: 3.97s
361:	learn: 0.4283967	total: 2.25s	remaining: 3.96s
362:	learn: 0.4283668	total: 2.25s	remaining: 3.95s
363:	learn: 0.4283290	total: 2.26s	remaining: 3.95s
364:	learn: 0.4282915	total: 2.27s	remaining: 3.94s
365:	learn: 0.4282465	total: 2.27s	remaining: 3.94s
366:	learn: 0.4282236	total: 2.28s	remaining: 3.93s
367:	learn: 0.4281917	total: 2.28s	remaining: 3.92s
368:	learn: 0.4281456	total: 2.29s	remaining: 3.92s
369:	learn: 0.4281172	total: 2.29s	remaining: 3.91s
370:	learn: 0.4280852	total: 2.3s	remaining: 3.9s
371:	learn: 0.4280492	total: 2.31s	remaining: 3.9s
372:	learn: 0.4280233	total: 2.31s	remaining: 3.89s
373:	learn: 0.4279917	total: 2.32s	remaining: 3.88s
374:	learn: 0.4279662	total: 2.32s	remaining: 3.87s
375:	learn: 0.4279400	total: 2.33s	remaining: 3.87s
376:	learn: 0.4279062	total: 2.34s	remaining: 3.86s
377:	learn: 0.4278597	total: 2.34s	remaining: 3.85s
378:	learn: 0.4278207	total: 2.35s	remaining: 3.85s
379:	learn: 0.4277815	total: 2.35s	remaining: 3.84s
380:	learn: 0.4277297	total: 2.36s	remaining: 3.83s
381:	learn: 0.4277221	total: 2.36s	remaining: 3.83s
382:	learn: 0.4276905	total: 2.37s	remaining: 3.82s
383:	learn: 0.4276700	total: 2.38s	remaining: 3.81s
384:	learn: 0.4276282	total: 2.38s	remaining: 3.81s
385:	learn: 0.4275886	total: 2.39s	remaining: 3.8s
386:	learn: 0.4275356	total: 2.39s	remaining: 3.79s