In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [5]:
df = pd.read_csv('diabetes.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
df.shape

(768, 9)

In [9]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [10]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
X = df.drop('Outcome',axis=1)
y=df['Outcome']

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)

In [15]:
model1 = AdaBoostClassifier(n_estimators=100,random_state=42)
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred1))
print('classification_score:',classification_report(y_test,y_pred1))
print('confusion_report:',confusion_matrix(y_test,y_pred1))

accuracy_score: 0.7402597402597403
classification_score:               precision    recall  f1-score   support

           0       0.81      0.78      0.79        99
           1       0.63      0.67      0.65        55

    accuracy                           0.74       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.74      0.74       154

confusion_report: [[77 22]
 [18 37]]

In [16]:
model2 = GradientBoostingClassifier()
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred2))
print('classification_score:',classification_report(y_test,y_pred2))
print('confusion_report:',confusion_matrix(y_test,y_pred2))

accuracy_score: 0.7402597402597403
classification_score:               precision    recall  f1-score   support

           0       0.81      0.78      0.79        99
           1       0.63      0.67      0.65        55

    accuracy                           0.74       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.74      0.74       154

confusion_report: [[77 22]
 [18 37]]

In [17]:
model3 = XGBClassifier()
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred3))
print('classification_score:',classification_report(y_test,y_pred3))
print('confusion_report:',confusion_matrix(y_test,y_pred3))

accuracy_score: 0.7207792207792207
classification_score:               precision    recall  f1-score   support

           0       0.82      0.73      0.77        99
           1       0.59      0.71      0.64        55

    accuracy                           0.72       154
   macro avg       0.70      0.72      0.71       154
weighted avg       0.74      0.72      0.73       154

confusion_report: [[72 27]
 [16 39]]

In [18]:
model4 = CatBoostClassifier()
model4.fit(X_train,y_train)
y_pred4 = model4.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred4))
print('classification_score:',classification_report(y_test,y_pred4))
print('confusion_report:',confusion_matrix(y_test,y_pred4))

Learning rate set to 0.008365
0:	learn: 0.6888461	total: 57.3ms	remaining: 57.3s
1:	learn: 0.6852948	total: 59.8ms	remaining: 29.8s
2:	learn: 0.6814512	total: 61.9ms	remaining: 20.6s
3:	learn: 0.6771557	total: 63.5ms	remaining: 15.8s
4:	learn: 0.6737050	total: 65.1ms	remaining: 13s
5:	learn: 0.6695565	total: 66.2ms	remaining: 11s
6:	learn: 0.6653279	total: 67.5ms	remaining: 9.57s
7:	learn: 0.6615001	total: 68.7ms	remaining: 8.52s
8:	learn: 0.6573795	total: 69.7ms	remaining: 7.68s
9:	learn: 0.6547598	total: 70.3ms	remaining: 6.96s
10:	learn: 0.6506556	total: 71.4ms	remaining: 6.42s
11:	learn: 0.6475214	total: 72.3ms	remaining: 5.96s
12:	learn: 0.6444544	total: 73.2ms	remaining: 5.56s
13:	learn: 0.6408373	total: 74.1ms	remaining: 5.22s
14:	learn: 0.6379785	total: 75.2ms	remaining: 4.93s
15:	learn: 0.6340365	total: 76.3ms	remaining: 4.69s
16:	learn: 0.6302563	total: 77.2ms	remaining: 4.46s
17:	learn: 0.6267500	total: 78ms	remaining: 4.25s
18:	learn: 0.6241854	total: 78.8ms	remaining: 4.07s
19:	learn: 0.6202820	total: 79.6ms	remaining: 3.9s
20:	learn: 0.6172584	total: 80.6ms	remaining: 3.75s
21:	learn: 0.6143071	total: 81.5ms	remaining: 3.62s
22:	learn: 0.6119328	total: 82.4ms	remaining: 3.5s
23:	learn: 0.6086191	total: 83.5ms	remaining: 3.39s
24:	learn: 0.6057496	total: 84.6ms	remaining: 3.3s
25:	learn: 0.6021204	total: 85.7ms	remaining: 3.21s
26:	learn: 0.5992122	total: 86.8ms	remaining: 3.13s
27:	learn: 0.5960207	total: 87.7ms	remaining: 3.04s
28:	learn: 0.5931694	total: 88.7ms	remaining: 2.97s
29:	learn: 0.5906845	total: 89.5ms	remaining: 2.89s
30:	learn: 0.5880027	total: 90.4ms	remaining: 2.83s
31:	learn: 0.5843697	total: 91.3ms	remaining: 2.76s
32:	learn: 0.5822897	total: 92.1ms	remaining: 2.7s
33:	learn: 0.5796353	total: 93ms	remaining: 2.64s
34:	learn: 0.5768816	total: 93.8ms	remaining: 2.58s
35:	learn: 0.5747707	total: 94.7ms	remaining: 2.54s
36:	learn: 0.5719336	total: 95.4ms	remaining: 2.48s
37:	learn: 0.5691629	total: 96.7ms	remaining: 2.45s
38:	learn: 0.5663484	total: 97.4ms	remaining: 2.4s
39:	learn: 0.5636383	total: 98.2ms	remaining: 2.36s
40:	learn: 0.5616496	total: 98.9ms	remaining: 2.31s
41:	learn: 0.5592387	total: 99.6ms	remaining: 2.27s
42:	learn: 0.5569822	total: 100ms	remaining: 2.23s
43:	learn: 0.5548518	total: 101ms	remaining: 2.2s
44:	learn: 0.5524668	total: 102ms	remaining: 2.16s
45:	learn: 0.5498939	total: 103ms	remaining: 2.13s
46:	learn: 0.5472891	total: 104ms	remaining: 2.1s
47:	learn: 0.5454316	total: 104ms	remaining: 2.07s
48:	learn: 0.5430967	total: 105ms	remaining: 2.04s
49:	learn: 0.5408602	total: 106ms	remaining: 2.01s
50:	learn: 0.5385445	total: 107ms	remaining: 1.98s
51:	learn: 0.5362814	total: 107ms	remaining: 1.95s
52:	learn: 0.5338999	total: 108ms	remaining: 1.93s
53:	learn: 0.5315141	total: 109ms	remaining: 1.9s
54:	learn: 0.5298964	total: 109ms	remaining: 1.88s
55:	learn: 0.5277119	total: 110ms	remaining: 1.86s
56:	learn: 0.5258114	total: 111ms	remaining: 1.83s
57:	learn: 0.5236151	total: 111ms	remaining: 1.81s
58:	learn: 0.5214331	total: 112ms	remaining: 1.79s
59:	learn: 0.5200545	total: 113ms	remaining: 1.77s
60:	learn: 0.5184092	total: 114ms	remaining: 1.75s
61:	learn: 0.5172024	total: 114ms	remaining: 1.73s
62:	learn: 0.5157505	total: 115ms	remaining: 1.71s
63:	learn: 0.5140858	total: 116ms	remaining: 1.69s
64:	learn: 0.5124856	total: 116ms	remaining: 1.68s
65:	learn: 0.5110932	total: 117ms	remaining: 1.66s
66:	learn: 0.5092065	total: 118ms	remaining: 1.64s
67:	learn: 0.5077362	total: 118ms	remaining: 1.62s
68:	learn: 0.5058397	total: 119ms	remaining: 1.61s
69:	learn: 0.5042625	total: 120ms	remaining: 1.59s
70:	learn: 0.5026993	total: 120ms	remaining: 1.57s
71:	learn: 0.5014052	total: 121ms	remaining: 1.56s
72:	learn: 0.5001301	total: 122ms	remaining: 1.54s
73:	learn: 0.4990980	total: 122ms	remaining: 1.53s
74:	learn: 0.4977947	total: 123ms	remaining: 1.51s
75:	learn: 0.4962355	total: 123ms	remaining: 1.5s
76:	learn: 0.4947456	total: 124ms	remaining: 1.49s
77:	learn: 0.4930937	total: 125ms	remaining: 1.47s
78:	learn: 0.4916759	total: 125ms	remaining: 1.46s
79:	learn: 0.4905317	total: 126ms	remaining: 1.44s
80:	learn: 0.4896594	total: 126ms	remaining: 1.43s
81:	learn: 0.4884264	total: 127ms	remaining: 1.42s
82:	learn: 0.4872018	total: 127ms	remaining: 1.4s
83:	learn: 0.4860993	total: 128ms	remaining: 1.39s
84:	learn: 0.4843570	total: 128ms	remaining: 1.38s
85:	learn: 0.4832355	total: 129ms	remaining: 1.37s
86:	learn: 0.4821001	total: 129ms	remaining: 1.36s
87:	learn: 0.4812578	total: 130ms	remaining: 1.35s
88:	learn: 0.4798436	total: 131ms	remaining: 1.34s
89:	learn: 0.4789739	total: 131ms	remaining: 1.32s
90:	learn: 0.4776863	total: 132ms	remaining: 1.31s
91:	learn: 0.4762932	total: 132ms	remaining: 1.31s
92:	learn: 0.4749633	total: 133ms	remaining: 1.3s
93:	learn: 0.4737469	total: 134ms	remaining: 1.29s
94:	learn: 0.4723321	total: 135ms	remaining: 1.28s
95:	learn: 0.4716209	total: 135ms	remaining: 1.27s
96:	learn: 0.4705730	total: 136ms	remaining: 1.26s
97:	learn: 0.4691420	total: 136ms	remaining: 1.25s
98:	learn: 0.4677659	total: 137ms	remaining: 1.25s
99:	learn: 0.4665580	total: 137ms	remaining: 1.24s
100:	learn: 0.4653637	total: 138ms	remaining: 1.23s
101:	learn: 0.4641399	total: 138ms	remaining: 1.22s
102:	learn: 0.4629789	total: 139ms	remaining: 1.21s
103:	learn: 0.4617653	total: 139ms	remaining: 1.2s
104:	learn: 0.4608705	total: 140ms	remaining: 1.19s
105:	learn: 0.4595830	total: 140ms	remaining: 1.18s
106:	learn: 0.4589061	total: 141ms	remaining: 1.18s
107:	learn: 0.4577206	total: 142ms	remaining: 1.17s
108:	learn: 0.4566499	total: 142ms	remaining: 1.16s
109:	learn: 0.4556670	total: 143ms	remaining: 1.16s
110:	learn: 0.4544914	total: 143ms	remaining: 1.15s
111:	learn: 0.4536519	total: 144ms	remaining: 1.14s
112:	learn: 0.4528048	total: 145ms	remaining: 1.13s
113:	learn: 0.4519335	total: 145ms	remaining: 1.13s
114:	learn: 0.4506029	total: 145ms	remaining: 1.12s
115:	learn: 0.4497879	total: 146ms	remaining: 1.11s
116:	learn: 0.4491042	total: 147ms	remaining: 1.11s
117:	learn: 0.4481642	total: 147ms	remaining: 1.1s
118:	learn: 0.4470190	total: 148ms	remaining: 1.09s
119:	learn: 0.4462757	total: 148ms	remaining: 1.09s
120:	learn: 0.4456190	total: 149ms	remaining: 1.08s
121:	learn: 0.4449676	total: 149ms	remaining: 1.07s
122:	learn: 0.4436794	total: 150ms	remaining: 1.07s
123:	learn: 0.4427215	total: 150ms	remaining: 1.06s
124:	learn: 0.4421028	total: 151ms	remaining: 1.06s
125:	learn: 0.4413592	total: 151ms	remaining: 1.05s
126:	learn: 0.4406469	total: 152ms	remaining: 1.04s
127:	learn: 0.4399805	total: 152ms	remaining: 1.04s
128:	learn: 0.4391655	total: 153ms	remaining: 1.03s
129:	learn: 0.4381043	total: 154ms	remaining: 1.03s
130:	learn: 0.4373584	total: 154ms	remaining: 1.02s
131:	learn: 0.4364998	total: 155ms	remaining: 1.02s
132:	learn: 0.4353819	total: 155ms	remaining: 1.01s
133:	learn: 0.4346081	total: 155ms	remaining: 1s
134:	learn: 0.4337789	total: 156ms	remaining: 999ms
135:	learn: 0.4330724	total: 157ms	remaining: 994ms
136:	learn: 0.4323308	total: 157ms	remaining: 989ms
137:	learn: 0.4315702	total: 157ms	remaining: 984ms
138:	learn: 0.4303481	total: 158ms	remaining: 978ms
139:	learn: 0.4296146	total: 159ms	remaining: 974ms
140:	learn: 0.4286671	total: 159ms	remaining: 969ms
141:	learn: 0.4280153	total: 160ms	remaining: 964ms
142:	learn: 0.4271254	total: 160ms	remaining: 959ms
143:	learn: 0.4263449	total: 161ms	remaining: 955ms
144:	learn: 0.4256156	total: 161ms	remaining: 950ms
145:	learn: 0.4248555	total: 162ms	remaining: 946ms
146:	learn: 0.4240772	total: 162ms	remaining: 941ms
147:	learn: 0.4234093	total: 163ms	remaining: 936ms
148:	learn: 0.4226308	total: 163ms	remaining: 933ms
149:	learn: 0.4217214	total: 164ms	remaining: 929ms
150:	learn: 0.4210300	total: 164ms	remaining: 925ms
151:	learn: 0.4205754	total: 165ms	remaining: 920ms
152:	learn: 0.4199658	total: 165ms	remaining: 916ms
153:	learn: 0.4193155	total: 166ms	remaining: 912ms
154:	learn: 0.4189619	total: 166ms	remaining: 908ms
155:	learn: 0.4181096	total: 167ms	remaining: 904ms
156:	learn: 0.4174695	total: 167ms	remaining: 899ms
157:	learn: 0.4169747	total: 168ms	remaining: 895ms
158:	learn: 0.4161359	total: 168ms	remaining: 891ms
159:	learn: 0.4155105	total: 169ms	remaining: 887ms
160:	learn: 0.4151776	total: 170ms	remaining: 884ms
161:	learn: 0.4144700	total: 170ms	remaining: 880ms
162:	learn: 0.4138323	total: 171ms	remaining: 877ms
163:	learn: 0.4129591	total: 171ms	remaining: 873ms
164:	learn: 0.4124059	total: 172ms	remaining: 869ms
165:	learn: 0.4119153	total: 172ms	remaining: 865ms
166:	learn: 0.4115124	total: 173ms	remaining: 861ms
167:	learn: 0.4111085	total: 173ms	remaining: 858ms
168:	learn: 0.4105580	total: 174ms	remaining: 854ms
169:	learn: 0.4096582	total: 174ms	remaining: 850ms
170:	learn: 0.4091702	total: 175ms	remaining: 847ms
171:	learn: 0.4085490	total: 175ms	remaining: 843ms
172:	learn: 0.4081177	total: 176ms	remaining: 840ms
173:	learn: 0.4074710	total: 176ms	remaining: 836ms
174:	learn: 0.4068740	total: 177ms	remaining: 833ms
175:	learn: 0.4061811	total: 177ms	remaining: 830ms
176:	learn: 0.4054775	total: 178ms	remaining: 827ms
177:	learn: 0.4046018	total: 178ms	remaining: 824ms
178:	learn: 0.4036644	total: 179ms	remaining: 821ms
179:	learn: 0.4031399	total: 180ms	remaining: 818ms
180:	learn: 0.4024575	total: 180ms	remaining: 815ms
181:	learn: 0.4020067	total: 181ms	remaining: 811ms
182:	learn: 0.4013149	total: 181ms	remaining: 808ms
183:	learn: 0.4008645	total: 182ms	remaining: 805ms
184:	learn: 0.4003129	total: 182ms	remaining: 802ms
185:	learn: 0.3997398	total: 182ms	remaining: 799ms
186:	learn: 0.3990625	total: 183ms	remaining: 795ms
187:	learn: 0.3984467	total: 184ms	remaining: 793ms
188:	learn: 0.3977803	total: 184ms	remaining: 790ms
189:	learn: 0.3973364	total: 185ms	remaining: 787ms
190:	learn: 0.3968922	total: 185ms	remaining: 784ms
191:	learn: 0.3961872	total: 186ms	remaining: 781ms
192:	learn: 0.3957258	total: 186ms	remaining: 778ms
193:	learn: 0.3952733	total: 187ms	remaining: 775ms
194:	learn: 0.3945192	total: 187ms	remaining: 772ms
195:	learn: 0.3941181	total: 188ms	remaining: 770ms
196:	learn: 0.3937600	total: 188ms	remaining: 768ms
197:	learn: 0.3933307	total: 189ms	remaining: 765ms
198:	learn: 0.3927724	total: 189ms	remaining: 762ms
199:	learn: 0.3922789	total: 190ms	remaining: 759ms
200:	learn: 0.3917904	total: 190ms	remaining: 757ms
201:	learn: 0.3913793	total: 191ms	remaining: 756ms
202:	learn: 0.3908707	total: 192ms	remaining: 753ms
203:	learn: 0.3904313	total: 192ms	remaining: 750ms
204:	learn: 0.3900547	total: 193ms	remaining: 748ms
205:	learn: 0.3894127	total: 194ms	remaining: 746ms
206:	learn: 0.3888602	total: 194ms	remaining: 743ms
207:	learn: 0.3883144	total: 195ms	remaining: 741ms
208:	learn: 0.3878031	total: 195ms	remaining: 738ms
209:	learn: 0.3873187	total: 195ms	remaining: 735ms
210:	learn: 0.3868053	total: 196ms	remaining: 733ms
211:	learn: 0.3863334	total: 196ms	remaining: 730ms
212:	learn: 0.3858486	total: 197ms	remaining: 727ms
213:	learn: 0.3851692	total: 197ms	remaining: 725ms
214:	learn: 0.3847092	total: 198ms	remaining: 722ms
215:	learn: 0.3843271	total: 198ms	remaining: 720ms
216:	learn: 0.3836253	total: 199ms	remaining: 718ms
217:	learn: 0.3832020	total: 199ms	remaining: 715ms
218:	learn: 0.3827751	total: 200ms	remaining: 713ms
219:	learn: 0.3824356	total: 200ms	remaining: 710ms
220:	learn: 0.3821184	total: 201ms	remaining: 708ms
221:	learn: 0.3817846	total: 201ms	remaining: 705ms
222:	learn: 0.3812811	total: 202ms	remaining: 703ms
223:	learn: 0.3808046	total: 202ms	remaining: 700ms
224:	learn: 0.3803732	total: 203ms	remaining: 698ms
225:	learn: 0.3797315	total: 203ms	remaining: 696ms
226:	learn: 0.3794664	total: 204ms	remaining: 693ms
227:	learn: 0.3790736	total: 204ms	remaining: 691ms
228:	learn: 0.3786730	total: 205ms	remaining: 689ms
229:	learn: 0.3782441	total: 205ms	remaining: 687ms
230:	learn: 0.3778242	total: 206ms	remaining: 685ms
231:	learn: 0.3773214	total: 206ms	remaining: 682ms
232:	learn: 0.3768130	total: 207ms	remaining: 680ms
233:	learn: 0.3763589	total: 207ms	remaining: 678ms
234:	learn: 0.3757441	total: 208ms	remaining: 676ms
235:	learn: 0.3751425	total: 208ms	remaining: 673ms
236:	learn: 0.3749290	total: 208ms	remaining: 671ms
237:	learn: 0.3744756	total: 209ms	remaining: 669ms
238:	learn: 0.3739188	total: 210ms	remaining: 667ms
239:	learn: 0.3733976	total: 210ms	remaining: 665ms
240:	learn: 0.3728969	total: 211ms	remaining: 664ms
241:	learn: 0.3725498	total: 211ms	remaining: 662ms
242:	learn: 0.3720639	total: 212ms	remaining: 659ms
243:	learn: 0.3718807	total: 212ms	remaining: 657ms
244:	learn: 0.3714040	total: 213ms	remaining: 655ms
245:	learn: 0.3709773	total: 213ms	remaining: 654ms
246:	learn: 0.3706683	total: 214ms	remaining: 653ms
247:	learn: 0.3702843	total: 215ms	remaining: 651ms
248:	learn: 0.3699533	total: 215ms	remaining: 649ms
249:	learn: 0.3696842	total: 216ms	remaining: 647ms
250:	learn: 0.3693169	total: 216ms	remaining: 645ms
251:	learn: 0.3688866	total: 217ms	remaining: 644ms
252:	learn: 0.3687176	total: 217ms	remaining: 642ms
253:	learn: 0.3684367	total: 218ms	remaining: 640ms
254:	learn: 0.3678852	total: 219ms	remaining: 639ms
255:	learn: 0.3674480	total: 220ms	remaining: 638ms
256:	learn: 0.3671187	total: 220ms	remaining: 636ms
257:	learn: 0.3667346	total: 221ms	remaining: 635ms
258:	learn: 0.3662970	total: 221ms	remaining: 633ms
259:	learn: 0.3658740	total: 222ms	remaining: 632ms
260:	learn: 0.3655194	total: 222ms	remaining: 630ms
261:	learn: 0.3648656	total: 223ms	remaining: 628ms
262:	learn: 0.3643298	total: 224ms	remaining: 626ms
263:	learn: 0.3640924	total: 224ms	remaining: 624ms
264:	learn: 0.3635798	total: 224ms	remaining: 623ms
265:	learn: 0.3630873	total: 226ms	remaining: 623ms
266:	learn: 0.3628199	total: 226ms	remaining: 621ms
267:	learn: 0.3626971	total: 227ms	remaining: 619ms
268:	learn: 0.3623804	total: 227ms	remaining: 617ms
269:	learn: 0.3620770	total: 228ms	remaining: 615ms
270:	learn: 0.3617273	total: 228ms	remaining: 613ms
271:	learn: 0.3614008	total: 228ms	remaining: 612ms
272:	learn: 0.3611552	total: 229ms	remaining: 610ms
273:	learn: 0.3606843	total: 229ms	remaining: 608ms
274:	learn: 0.3602722	total: 230ms	remaining: 606ms
275:	learn: 0.3600288	total: 230ms	remaining: 604ms
276:	learn: 0.3598617	total: 231ms	remaining: 603ms
277:	learn: 0.3594875	total: 232ms	remaining: 602ms
278:	learn: 0.3590408	total: 232ms	remaining: 600ms
279:	learn: 0.3586899	total: 233ms	remaining: 598ms
280:	learn: 0.3583034	total: 233ms	remaining: 596ms
281:	learn: 0.3579132	total: 234ms	remaining: 595ms
282:	learn: 0.3576729	total: 234ms	remaining: 593ms
283:	learn: 0.3571787	total: 235ms	remaining: 591ms
284:	learn: 0.3566762	total: 235ms	remaining: 590ms
285:	learn: 0.3562708	total: 235ms	remaining: 588ms
286:	learn: 0.3557267	total: 236ms	remaining: 586ms
287:	learn: 0.3552781	total: 236ms	remaining: 585ms
288:	learn: 0.3549409	total: 237ms	remaining: 583ms
289:	learn: 0.3546656	total: 237ms	remaining: 581ms
290:	learn: 0.3544690	total: 238ms	remaining: 579ms
291:	learn: 0.3541891	total: 238ms	remaining: 578ms
292:	learn: 0.3536886	total: 239ms	remaining: 577ms
293:	learn: 0.3534467	total: 240ms	remaining: 575ms
294:	learn: 0.3531089	total: 240ms	remaining: 574ms
295:	learn: 0.3528610	total: 240ms	remaining: 572ms
296:	learn: 0.3526418	total: 241ms	remaining: 570ms
297:	learn: 0.3524035	total: 242ms	remaining: 569ms
298:	learn: 0.3521499	total: 242ms	remaining: 567ms
299:	learn: 0.3518337	total: 242ms	remaining: 566ms
300:	learn: 0.3515808	total: 243ms	remaining: 564ms
301:	learn: 0.3512031	total: 243ms	remaining: 563ms
302:	learn: 0.3508650	total: 244ms	remaining: 562ms
303:	learn: 0.3505356	total: 245ms	remaining: 560ms
304:	learn: 0.3503006	total: 245ms	remaining: 559ms
305:	learn: 0.3500748	total: 246ms	remaining: 557ms
306:	learn: 0.3499309	total: 246ms	remaining: 556ms
307:	learn: 0.3496036	total: 247ms	remaining: 554ms
308:	learn: 0.3492387	total: 247ms	remaining: 552ms
309:	learn: 0.3487933	total: 248ms	remaining: 551ms
310:	learn: 0.3484877	total: 248ms	remaining: 550ms
311:	learn: 0.3481974	total: 249ms	remaining: 548ms
312:	learn: 0.3479131	total: 249ms	remaining: 547ms
313:	learn: 0.3475688	total: 250ms	remaining: 545ms
314:	learn: 0.3473130	total: 250ms	remaining: 544ms
315:	learn: 0.3471255	total: 251ms	remaining: 542ms
316:	learn: 0.3468599	total: 251ms	remaining: 541ms
317:	learn: 0.3464432	total: 252ms	remaining: 540ms
318:	learn: 0.3461385	total: 252ms	remaining: 538ms
319:	learn: 0.3458934	total: 253ms	remaining: 537ms
320:	learn: 0.3455099	total: 253ms	remaining: 535ms
321:	learn: 0.3451798	total: 254ms	remaining: 534ms
322:	learn: 0.3449981	total: 254ms	remaining: 533ms
323:	learn: 0.3446577	total: 255ms	remaining: 531ms
324:	learn: 0.3442314	total: 255ms	remaining: 530ms
325:	learn: 0.3440395	total: 256ms	remaining: 528ms
326:	learn: 0.3437107	total: 256ms	remaining: 527ms
327:	learn: 0.3432788	total: 257ms	remaining: 526ms
328:	learn: 0.3429801	total: 257ms	remaining: 524ms
329:	learn: 0.3426081	total: 258ms	remaining: 523ms
330:	learn: 0.3423723	total: 258ms	remaining: 522ms
331:	learn: 0.3420906	total: 259ms	remaining: 521ms
332:	learn: 0.3416388	total: 259ms	remaining: 519ms
333:	learn: 0.3413088	total: 260ms	remaining: 518ms
334:	learn: 0.3411645	total: 260ms	remaining: 517ms
335:	learn: 0.3406571	total: 261ms	remaining: 516ms
336:	learn: 0.3403946	total: 261ms	remaining: 514ms
337:	learn: 0.3400055	total: 262ms	remaining: 513ms
338:	learn: 0.3398076	total: 262ms	remaining: 512ms
339:	learn: 0.3395733	total: 263ms	remaining: 510ms
340:	learn: 0.3391213	total: 263ms	remaining: 509ms
341:	learn: 0.3388086	total: 264ms	remaining: 508ms
342:	learn: 0.3385927	total: 265ms	remaining: 507ms
343:	learn: 0.3381567	total: 265ms	remaining: 506ms
344:	learn: 0.3379935	total: 266ms	remaining: 504ms
345:	learn: 0.3375235	total: 266ms	remaining: 503ms
346:	learn: 0.3372451	total: 267ms	remaining: 502ms
347:	learn: 0.3370608	total: 267ms	remaining: 501ms
348:	learn: 0.3368476	total: 268ms	remaining: 499ms
349:	learn: 0.3365906	total: 268ms	remaining: 498ms
350:	learn: 0.3361170	total: 269ms	remaining: 497ms
351:	learn: 0.3358873	total: 269ms	remaining: 496ms
352:	learn: 0.3355940	total: 270ms	remaining: 494ms
353:	learn: 0.3352237	total: 270ms	remaining: 493ms
354:	learn: 0.3347619	total: 271ms	remaining: 492ms
355:	learn: 0.3345379	total: 271ms	remaining: 491ms
356:	learn: 0.3342033	total: 272ms	remaining: 490ms
357:	learn: 0.3339550	total: 273ms	remaining: 489ms
358:	learn: 0.3336568	total: 273ms	remaining: 488ms
359:	learn: 0.3333355	total: 274ms	remaining: 487ms
360:	learn: 0.3330375	total: 274ms	remaining: 485ms
361:	learn: 0.3327273	total: 275ms	remaining: 484ms
362:	learn: 0.3322852	total: 275ms	remaining: 483ms
363:	learn: 0.3319899	total: 276ms	remaining: 482ms
364:	learn: 0.3316090	total: 277ms	remaining: 481ms
365:	learn: 0.3314353	total: 277ms	remaining: 480ms
366:	learn: 0.3309902	total: 278ms	remaining: 479ms
367:	learn: 0.3307867	total: 278ms	remaining: 478ms
368:	learn: 0.3306132	total: 279ms	remaining: 477ms
369:	learn: 0.3302896	total: 279ms	remaining: 475ms
370:	learn: 0.3300495	total: 280ms	remaining: 474ms
371:	learn: 0.3296605	total: 281ms	remaining: 474ms
372:	learn: 0.3294193	total: 281ms	remaining: 472ms
373:	learn: 0.3290280	total: 281ms	remaining: 471ms
374:	learn: 0.3288922	total: 282ms	remaining: 470ms
375:	learn: 0.3286426	total: 282ms	remaining: 469ms
376:	learn: 0.3283893	total: 283ms	remaining: 467ms
377:	learn: 0.3282660	total: 284ms	remaining: 467ms
378:	learn: 0.3280415	total: 285ms	remaining: 466ms
379:	learn: 0.3278386	total: 285ms	remaining: 465ms
380:	learn: 0.3276117	total: 286ms	remaining: 464ms
381:	learn: 0.3274689	total: 286ms	remaining: 463ms
382:	learn: 0.3271163	total: 287ms	remaining: 462ms
383:	learn: 0.3267883	total: 287ms	remaining: 461ms
384:	learn: 0.3265567	total: 288ms	remaining: 460ms

In [19]:
model5 = LGBMClassifier()
model5.fit(X_train,y_train)
y_pred5 = model5.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred5))
print('classification_score:',classification_report(y_test,y_pred5))
print('confusion_report:',confusion_matrix(y_test,y_pred5))

[LightGBM] [Info] Number of positive: 213, number of negative: 401
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000229 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 664
[LightGBM] [Info] Number of data points in the train set: 614, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.346906 -> initscore=-0.632669
[LightGBM] [Info] Start training from score -0.632669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
accuracy_score: 0.7207792207792207
classification_score:               precision    recall  f1-score   support

           0       0.81      0.74      0.77        99
           1       0.59      0.69      0.64        55

    accuracy                           0.72       154
   macro avg       0.70      0.71      0.71       154
weighted avg       0.73      0.72      0.72       154

confusion_report: [[73 26]
 [17 38]]