In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [4]:
df = pd.read_csv('student-mat.csv')

In [6]:
df.shape

(395, 33)

In [7]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [9]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [10]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [11]:
df = df.drop(["G1","G2"], axis=1)

In [12]:
df = pd.get_dummies(df, drop_first=True)

In [13]:
X = df.drop("G3", axis=1)
y = df["G3"]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [16]:
model1 = AdaBoostRegressor(n_estimators=100,random_state=42)
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred1))
print("MAE:",mean_absolute_error(y_test,y_pred1))
print('r2_score:',r2_score(y_test,y_pred1))

MSE: 18.776873988500828
MAE: 3.5088825600144644
r2_score: 0.08428038506678293

In [29]:
model2 = GradientBoostingRegressor(n_estimators=500,learning_rate=0.05,max_depth=3)
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred2))
print("MAE:",mean_absolute_error(y_test,y_pred2))
print('r2_score:',r2_score(y_test,y_pred2))

MSE: 15.953812127693743
MAE: 3.2529050329453306
r2_score: 0.22195682267264216

In [19]:
model3 = XGBRegressor()
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred3))
print("MAE:",mean_absolute_error(y_test,y_pred3))
print('r2_score:',r2_score(y_test,y_pred3))

MSE: 17.1763973236084
MAE: 3.399308681488037
r2_score: 0.16233325004577637

In [20]:
model4 = CatBoostRegressor()
model4.fit(X_train,y_train)
y_pred4 = model4.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred4))
print("MAE:",mean_absolute_error(y_test,y_pred4))
print('r2_score:',r2_score(y_test,y_pred4))

Learning rate set to 0.03413
0:	learn: 4.5473760	total: 58.3ms	remaining: 58.2s
1:	learn: 4.5076819	total: 60.4ms	remaining: 30.1s
2:	learn: 4.4776813	total: 63ms	remaining: 20.9s
3:	learn: 4.4477170	total: 65.3ms	remaining: 16.3s
4:	learn: 4.4189096	total: 67.1ms	remaining: 13.3s
5:	learn: 4.3844904	total: 68.6ms	remaining: 11.4s
6:	learn: 4.3531550	total: 70.2ms	remaining: 9.95s
7:	learn: 4.3195445	total: 71.7ms	remaining: 8.89s
8:	learn: 4.2899494	total: 72.8ms	remaining: 8.01s
9:	learn: 4.2643677	total: 73.9ms	remaining: 7.32s
10:	learn: 4.2368744	total: 75.1ms	remaining: 6.75s
11:	learn: 4.2051917	total: 76.2ms	remaining: 6.27s
12:	learn: 4.1792562	total: 77.3ms	remaining: 5.87s
13:	learn: 4.1566232	total: 78.4ms	remaining: 5.52s
14:	learn: 4.1271514	total: 79.6ms	remaining: 5.23s
15:	learn: 4.1022129	total: 82.1ms	remaining: 5.05s
16:	learn: 4.0805827	total: 84.4ms	remaining: 4.88s
17:	learn: 4.0504529	total: 86.1ms	remaining: 4.7s
18:	learn: 4.0232852	total: 87.9ms	remaining: 4.54s
19:	learn: 4.0023542	total: 89.5ms	remaining: 4.38s
20:	learn: 3.9758663	total: 90.9ms	remaining: 4.24s
21:	learn: 3.9581355	total: 92.6ms	remaining: 4.12s
22:	learn: 3.9401561	total: 94.3ms	remaining: 4s
23:	learn: 3.9194115	total: 95.8ms	remaining: 3.9s
24:	learn: 3.9018355	total: 97.5ms	remaining: 3.8s
25:	learn: 3.8772593	total: 99ms	remaining: 3.71s
26:	learn: 3.8616682	total: 101ms	remaining: 3.62s
27:	learn: 3.8420300	total: 102ms	remaining: 3.54s
28:	learn: 3.8313365	total: 103ms	remaining: 3.46s
29:	learn: 3.8080174	total: 105ms	remaining: 3.38s
30:	learn: 3.7930160	total: 106ms	remaining: 3.31s
31:	learn: 3.7783556	total: 107ms	remaining: 3.25s
32:	learn: 3.7705644	total: 109ms	remaining: 3.18s
33:	learn: 3.7567122	total: 110ms	remaining: 3.12s
34:	learn: 3.7384380	total: 111ms	remaining: 3.06s
35:	learn: 3.7276022	total: 112ms	remaining: 3s
36:	learn: 3.7099775	total: 113ms	remaining: 2.95s
37:	learn: 3.6964327	total: 114ms	remaining: 2.9s
38:	learn: 3.6832502	total: 115ms	remaining: 2.85s
39:	learn: 3.6626568	total: 117ms	remaining: 2.8s
40:	learn: 3.6485094	total: 118ms	remaining: 2.75s
41:	learn: 3.6437515	total: 118ms	remaining: 2.69s
42:	learn: 3.6215620	total: 119ms	remaining: 2.65s
43:	learn: 3.6054096	total: 120ms	remaining: 2.61s
44:	learn: 3.5891519	total: 121ms	remaining: 2.57s
45:	learn: 3.5814097	total: 122ms	remaining: 2.54s
46:	learn: 3.5665670	total: 123ms	remaining: 2.5s
47:	learn: 3.5474379	total: 124ms	remaining: 2.46s
48:	learn: 3.5323062	total: 125ms	remaining: 2.43s
49:	learn: 3.5192247	total: 126ms	remaining: 2.4s
50:	learn: 3.5029826	total: 127ms	remaining: 2.37s
51:	learn: 3.4928142	total: 128ms	remaining: 2.34s
52:	learn: 3.4760135	total: 129ms	remaining: 2.31s
53:	learn: 3.4537839	total: 130ms	remaining: 2.28s
54:	learn: 3.4440035	total: 131ms	remaining: 2.25s
55:	learn: 3.4276456	total: 132ms	remaining: 2.22s
56:	learn: 3.4150491	total: 133ms	remaining: 2.19s
57:	learn: 3.4025421	total: 134ms	remaining: 2.17s
58:	learn: 3.3926625	total: 134ms	remaining: 2.14s
59:	learn: 3.3812378	total: 135ms	remaining: 2.12s
60:	learn: 3.3715650	total: 136ms	remaining: 2.09s
61:	learn: 3.3582829	total: 137ms	remaining: 2.07s
62:	learn: 3.3435836	total: 138ms	remaining: 2.05s
63:	learn: 3.3316561	total: 139ms	remaining: 2.03s
64:	learn: 3.3250176	total: 139ms	remaining: 2s
65:	learn: 3.3120935	total: 140ms	remaining: 1.98s
66:	learn: 3.3021730	total: 141ms	remaining: 1.96s
67:	learn: 3.2927806	total: 142ms	remaining: 1.94s
68:	learn: 3.2848764	total: 143ms	remaining: 1.92s
69:	learn: 3.2786022	total: 143ms	remaining: 1.9s
70:	learn: 3.2666923	total: 144ms	remaining: 1.88s
71:	learn: 3.2515684	total: 145ms	remaining: 1.86s
72:	learn: 3.2429181	total: 146ms	remaining: 1.85s
73:	learn: 3.2372123	total: 146ms	remaining: 1.83s
74:	learn: 3.2279380	total: 147ms	remaining: 1.81s
75:	learn: 3.2218482	total: 148ms	remaining: 1.8s
76:	learn: 3.2108839	total: 149ms	remaining: 1.78s
77:	learn: 3.2021894	total: 149ms	remaining: 1.76s
78:	learn: 3.1952831	total: 150ms	remaining: 1.75s
79:	learn: 3.1830233	total: 151ms	remaining: 1.73s
80:	learn: 3.1797237	total: 151ms	remaining: 1.71s
81:	learn: 3.1688693	total: 152ms	remaining: 1.7s
82:	learn: 3.1526769	total: 152ms	remaining: 1.68s
83:	learn: 3.1456040	total: 153ms	remaining: 1.67s
84:	learn: 3.1386333	total: 154ms	remaining: 1.66s
85:	learn: 3.1270514	total: 155ms	remaining: 1.64s
86:	learn: 3.1214733	total: 155ms	remaining: 1.63s
87:	learn: 3.1112953	total: 156ms	remaining: 1.62s
88:	learn: 3.1010828	total: 157ms	remaining: 1.6s
89:	learn: 3.0911318	total: 157ms	remaining: 1.59s
90:	learn: 3.0827190	total: 158ms	remaining: 1.58s
91:	learn: 3.0690037	total: 159ms	remaining: 1.57s
92:	learn: 3.0556008	total: 159ms	remaining: 1.55s
93:	learn: 3.0468447	total: 160ms	remaining: 1.54s
94:	learn: 3.0419716	total: 161ms	remaining: 1.53s
95:	learn: 3.0345064	total: 162ms	remaining: 1.52s
96:	learn: 3.0273574	total: 162ms	remaining: 1.51s
97:	learn: 3.0124497	total: 163ms	remaining: 1.5s
98:	learn: 3.0008188	total: 164ms	remaining: 1.49s
99:	learn: 2.9907064	total: 164ms	remaining: 1.48s
100:	learn: 2.9832387	total: 165ms	remaining: 1.47s
101:	learn: 2.9722997	total: 166ms	remaining: 1.46s
102:	learn: 2.9621844	total: 166ms	remaining: 1.45s
103:	learn: 2.9572459	total: 167ms	remaining: 1.44s
104:	learn: 2.9469573	total: 168ms	remaining: 1.43s
105:	learn: 2.9401734	total: 168ms	remaining: 1.42s
106:	learn: 2.9270367	total: 169ms	remaining: 1.41s
107:	learn: 2.9230618	total: 170ms	remaining: 1.4s
108:	learn: 2.9170987	total: 170ms	remaining: 1.39s
109:	learn: 2.9130402	total: 171ms	remaining: 1.38s
110:	learn: 2.9060137	total: 172ms	remaining: 1.37s
111:	learn: 2.8972591	total: 172ms	remaining: 1.36s
112:	learn: 2.8875711	total: 173ms	remaining: 1.36s
113:	learn: 2.8813245	total: 174ms	remaining: 1.35s
114:	learn: 2.8723227	total: 174ms	remaining: 1.34s
115:	learn: 2.8633105	total: 175ms	remaining: 1.33s
116:	learn: 2.8577880	total: 176ms	remaining: 1.32s
117:	learn: 2.8467322	total: 176ms	remaining: 1.32s
118:	learn: 2.8377723	total: 177ms	remaining: 1.31s
119:	learn: 2.8331233	total: 178ms	remaining: 1.3s
120:	learn: 2.8282304	total: 178ms	remaining: 1.29s
121:	learn: 2.8207170	total: 179ms	remaining: 1.29s
122:	learn: 2.8151729	total: 180ms	remaining: 1.28s
123:	learn: 2.8042700	total: 180ms	remaining: 1.27s
124:	learn: 2.7963592	total: 181ms	remaining: 1.27s
125:	learn: 2.7913046	total: 182ms	remaining: 1.26s
126:	learn: 2.7827697	total: 183ms	remaining: 1.25s
127:	learn: 2.7688639	total: 183ms	remaining: 1.25s
128:	learn: 2.7628003	total: 184ms	remaining: 1.24s
129:	learn: 2.7555615	total: 185ms	remaining: 1.24s
130:	learn: 2.7464799	total: 186ms	remaining: 1.23s
131:	learn: 2.7429775	total: 186ms	remaining: 1.22s
132:	learn: 2.7326418	total: 187ms	remaining: 1.22s
133:	learn: 2.7254595	total: 188ms	remaining: 1.21s
134:	learn: 2.7150161	total: 188ms	remaining: 1.21s
135:	learn: 2.7122955	total: 189ms	remaining: 1.2s
136:	learn: 2.7064972	total: 190ms	remaining: 1.19s
137:	learn: 2.6998497	total: 190ms	remaining: 1.19s
138:	learn: 2.6890041	total: 191ms	remaining: 1.18s
139:	learn: 2.6787050	total: 192ms	remaining: 1.18s
140:	learn: 2.6667051	total: 193ms	remaining: 1.18s
141:	learn: 2.6604362	total: 194ms	remaining: 1.17s
142:	learn: 2.6499731	total: 194ms	remaining: 1.16s
143:	learn: 2.6379824	total: 195ms	remaining: 1.16s
144:	learn: 2.6374549	total: 195ms	remaining: 1.15s
145:	learn: 2.6277062	total: 196ms	remaining: 1.14s
146:	learn: 2.6204116	total: 196ms	remaining: 1.14s
147:	learn: 2.6122576	total: 197ms	remaining: 1.13s
148:	learn: 2.6058947	total: 198ms	remaining: 1.13s
149:	learn: 2.5942785	total: 199ms	remaining: 1.12s
150:	learn: 2.5850686	total: 199ms	remaining: 1.12s
151:	learn: 2.5751816	total: 200ms	remaining: 1.11s
152:	learn: 2.5697200	total: 201ms	remaining: 1.11s
153:	learn: 2.5609935	total: 201ms	remaining: 1.1s
154:	learn: 2.5549355	total: 202ms	remaining: 1.1s
155:	learn: 2.5441029	total: 203ms	remaining: 1.1s
156:	learn: 2.5401875	total: 203ms	remaining: 1.09s
157:	learn: 2.5343587	total: 204ms	remaining: 1.09s
158:	learn: 2.5255929	total: 205ms	remaining: 1.08s
159:	learn: 2.5171189	total: 205ms	remaining: 1.08s
160:	learn: 2.5169700	total: 206ms	remaining: 1.07s
161:	learn: 2.5097214	total: 206ms	remaining: 1.07s
162:	learn: 2.5026286	total: 207ms	remaining: 1.06s
163:	learn: 2.4912956	total: 208ms	remaining: 1.06s
164:	learn: 2.4808774	total: 208ms	remaining: 1.05s
165:	learn: 2.4747204	total: 209ms	remaining: 1.05s
166:	learn: 2.4669926	total: 210ms	remaining: 1.04s
167:	learn: 2.4577916	total: 210ms	remaining: 1.04s
168:	learn: 2.4479074	total: 211ms	remaining: 1.04s
169:	learn: 2.4378255	total: 212ms	remaining: 1.03s
170:	learn: 2.4284874	total: 212ms	remaining: 1.03s
171:	learn: 2.4246890	total: 213ms	remaining: 1.02s
172:	learn: 2.4108386	total: 214ms	remaining: 1.02s
173:	learn: 2.4013713	total: 215ms	remaining: 1.02s
174:	learn: 2.3934790	total: 215ms	remaining: 1.01s
175:	learn: 2.3891854	total: 216ms	remaining: 1.01s
176:	learn: 2.3812467	total: 217ms	remaining: 1.01s
177:	learn: 2.3763667	total: 218ms	remaining: 1s
178:	learn: 2.3643749	total: 218ms	remaining: 1s
179:	learn: 2.3536766	total: 220ms	remaining: 1s
180:	learn: 2.3460770	total: 220ms	remaining: 997ms
181:	learn: 2.3393125	total: 221ms	remaining: 994ms
182:	learn: 2.3364701	total: 222ms	remaining: 990ms
183:	learn: 2.3278700	total: 223ms	remaining: 987ms
184:	learn: 2.3202891	total: 223ms	remaining: 983ms
185:	learn: 2.3090014	total: 224ms	remaining: 980ms
186:	learn: 2.3049436	total: 225ms	remaining: 977ms
187:	learn: 2.2980775	total: 225ms	remaining: 973ms
188:	learn: 2.2935518	total: 226ms	remaining: 970ms
189:	learn: 2.2837641	total: 227ms	remaining: 967ms
190:	learn: 2.2774384	total: 227ms	remaining: 963ms
191:	learn: 2.2727546	total: 228ms	remaining: 960ms
192:	learn: 2.2653483	total: 229ms	remaining: 957ms
193:	learn: 2.2603532	total: 229ms	remaining: 953ms
194:	learn: 2.2580142	total: 230ms	remaining: 950ms
195:	learn: 2.2517961	total: 231ms	remaining: 947ms
196:	learn: 2.2443191	total: 231ms	remaining: 944ms
197:	learn: 2.2422276	total: 232ms	remaining: 941ms
198:	learn: 2.2355899	total: 233ms	remaining: 937ms
199:	learn: 2.2291730	total: 234ms	remaining: 934ms
200:	learn: 2.2229827	total: 234ms	remaining: 931ms
201:	learn: 2.2168141	total: 235ms	remaining: 929ms
202:	learn: 2.2141161	total: 236ms	remaining: 926ms
203:	learn: 2.2076493	total: 236ms	remaining: 923ms
204:	learn: 2.2018156	total: 237ms	remaining: 920ms
205:	learn: 2.1953698	total: 238ms	remaining: 917ms
206:	learn: 2.1933026	total: 239ms	remaining: 914ms
207:	learn: 2.1881035	total: 239ms	remaining: 911ms
208:	learn: 2.1832616	total: 240ms	remaining: 909ms
209:	learn: 2.1788458	total: 241ms	remaining: 906ms
210:	learn: 2.1735798	total: 241ms	remaining: 903ms
211:	learn: 2.1707887	total: 242ms	remaining: 900ms
212:	learn: 2.1665472	total: 243ms	remaining: 898ms
213:	learn: 2.1545828	total: 244ms	remaining: 895ms
214:	learn: 2.1495797	total: 244ms	remaining: 892ms
215:	learn: 2.1454806	total: 245ms	remaining: 890ms
216:	learn: 2.1403075	total: 246ms	remaining: 887ms
217:	learn: 2.1386373	total: 246ms	remaining: 884ms
218:	learn: 2.1306540	total: 247ms	remaining: 882ms
219:	learn: 2.1217301	total: 248ms	remaining: 879ms
220:	learn: 2.1191785	total: 249ms	remaining: 876ms
221:	learn: 2.1167514	total: 249ms	remaining: 874ms
222:	learn: 2.1087969	total: 250ms	remaining: 871ms
223:	learn: 2.1053896	total: 251ms	remaining: 869ms
224:	learn: 2.1006113	total: 251ms	remaining: 866ms
225:	learn: 2.0951421	total: 252ms	remaining: 864ms
226:	learn: 2.0910822	total: 253ms	remaining: 861ms
227:	learn: 2.0892110	total: 254ms	remaining: 859ms
228:	learn: 2.0841021	total: 254ms	remaining: 856ms
229:	learn: 2.0763068	total: 255ms	remaining: 854ms
230:	learn: 2.0679884	total: 256ms	remaining: 851ms
231:	learn: 2.0657715	total: 257ms	remaining: 849ms
232:	learn: 2.0613302	total: 257ms	remaining: 847ms
233:	learn: 2.0545618	total: 258ms	remaining: 845ms
234:	learn: 2.0506163	total: 259ms	remaining: 842ms
235:	learn: 2.0442098	total: 259ms	remaining: 840ms
236:	learn: 2.0381626	total: 260ms	remaining: 837ms
237:	learn: 2.0357084	total: 261ms	remaining: 835ms
238:	learn: 2.0288502	total: 261ms	remaining: 833ms
239:	learn: 2.0239803	total: 262ms	remaining: 830ms
240:	learn: 2.0198181	total: 263ms	remaining: 828ms
241:	learn: 2.0164890	total: 264ms	remaining: 826ms
242:	learn: 2.0134126	total: 264ms	remaining: 823ms
243:	learn: 2.0064547	total: 265ms	remaining: 821ms
244:	learn: 2.0004372	total: 266ms	remaining: 819ms
245:	learn: 1.9938548	total: 266ms	remaining: 817ms
246:	learn: 1.9878947	total: 267ms	remaining: 815ms
247:	learn: 1.9841570	total: 268ms	remaining: 812ms
248:	learn: 1.9780273	total: 269ms	remaining: 810ms
249:	learn: 1.9710410	total: 269ms	remaining: 808ms
250:	learn: 1.9663903	total: 270ms	remaining: 806ms
251:	learn: 1.9590755	total: 271ms	remaining: 804ms
252:	learn: 1.9533081	total: 271ms	remaining: 801ms
253:	learn: 1.9483143	total: 272ms	remaining: 799ms
254:	learn: 1.9419473	total: 273ms	remaining: 797ms
255:	learn: 1.9401771	total: 274ms	remaining: 795ms
256:	learn: 1.9308179	total: 274ms	remaining: 793ms
257:	learn: 1.9286187	total: 275ms	remaining: 791ms
258:	learn: 1.9251302	total: 276ms	remaining: 789ms
259:	learn: 1.9197950	total: 276ms	remaining: 786ms
260:	learn: 1.9111960	total: 277ms	remaining: 784ms
261:	learn: 1.9045423	total: 278ms	remaining: 782ms
262:	learn: 1.8983427	total: 278ms	remaining: 780ms
263:	learn: 1.8944114	total: 279ms	remaining: 778ms
264:	learn: 1.8890518	total: 280ms	remaining: 776ms
265:	learn: 1.8823462	total: 281ms	remaining: 774ms
266:	learn: 1.8778285	total: 281ms	remaining: 772ms
267:	learn: 1.8776004	total: 282ms	remaining: 770ms
268:	learn: 1.8737582	total: 283ms	remaining: 768ms
269:	learn: 1.8712021	total: 283ms	remaining: 766ms
270:	learn: 1.8705734	total: 284ms	remaining: 764ms
271:	learn: 1.8634468	total: 285ms	remaining: 762ms
272:	learn: 1.8592598	total: 286ms	remaining: 760ms
273:	learn: 1.8513220	total: 286ms	remaining: 758ms
274:	learn: 1.8454654	total: 287ms	remaining: 756ms
275:	learn: 1.8448788	total: 288ms	remaining: 754ms
276:	learn: 1.8432499	total: 288ms	remaining: 752ms
277:	learn: 1.8345300	total: 289ms	remaining: 750ms
278:	learn: 1.8310357	total: 290ms	remaining: 748ms
279:	learn: 1.8251495	total: 290ms	remaining: 747ms
280:	learn: 1.8236379	total: 291ms	remaining: 745ms
281:	learn: 1.8229916	total: 292ms	remaining: 743ms
282:	learn: 1.8148122	total: 292ms	remaining: 741ms
283:	learn: 1.8079116	total: 293ms	remaining: 739ms
284:	learn: 1.8051128	total: 294ms	remaining: 737ms
285:	learn: 1.7980258	total: 295ms	remaining: 735ms
286:	learn: 1.7974843	total: 295ms	remaining: 733ms
287:	learn: 1.7958916	total: 296ms	remaining: 732ms
288:	learn: 1.7948440	total: 297ms	remaining: 730ms
289:	learn: 1.7870975	total: 297ms	remaining: 728ms
290:	learn: 1.7841606	total: 298ms	remaining: 726ms
291:	learn: 1.7784646	total: 299ms	remaining: 724ms
292:	learn: 1.7778556	total: 299ms	remaining: 722ms
293:	learn: 1.7736995	total: 300ms	remaining: 721ms
294:	learn: 1.7680891	total: 301ms	remaining: 719ms
295:	learn: 1.7618198	total: 301ms	remaining: 717ms
296:	learn: 1.7613011	total: 302ms	remaining: 715ms
297:	learn: 1.7583681	total: 303ms	remaining: 714ms
298:	learn: 1.7541913	total: 304ms	remaining: 712ms
299:	learn: 1.7509283	total: 304ms	remaining: 710ms
300:	learn: 1.7468966	total: 305ms	remaining: 708ms
301:	learn: 1.7463651	total: 306ms	remaining: 707ms
302:	learn: 1.7447403	total: 306ms	remaining: 705ms
303:	learn: 1.7421664	total: 307ms	remaining: 703ms
304:	learn: 1.7373694	total: 308ms	remaining: 702ms
305:	learn: 1.7337629	total: 309ms	remaining: 700ms
306:	learn: 1.7332899	total: 310ms	remaining: 699ms
307:	learn: 1.7242893	total: 310ms	remaining: 697ms
308:	learn: 1.7226480	total: 311ms	remaining: 695ms
309:	learn: 1.7206731	total: 312ms	remaining: 694ms
310:	learn: 1.7201896	total: 312ms	remaining: 692ms
311:	learn: 1.7149820	total: 313ms	remaining: 690ms
312:	learn: 1.7102370	total: 314ms	remaining: 688ms
313:	learn: 1.7067770	total: 314ms	remaining: 687ms
314:	learn: 1.7010205	total: 315ms	remaining: 685ms
315:	learn: 1.7004739	total: 316ms	remaining: 683ms
316:	learn: 1.6967968	total: 316ms	remaining: 682ms
317:	learn: 1.6925238	total: 317ms	remaining: 680ms
318:	learn: 1.6883937	total: 318ms	remaining: 679ms
319:	learn: 1.6879712	total: 319ms	remaining: 678ms
320:	learn: 1.6854260	total: 320ms	remaining: 677ms
321:	learn: 1.6798567	total: 321ms	remaining: 675ms
322:	learn: 1.6755026	total: 321ms	remaining: 673ms
323:	learn: 1.6736867	total: 322ms	remaining: 672ms
324:	learn: 1.6688834	total: 323ms	remaining: 670ms
325:	learn: 1.6631325	total: 323ms	remaining: 669ms
326:	learn: 1.6593026	total: 324ms	remaining: 667ms
327:	learn: 1.6567765	total: 325ms	remaining: 665ms
328:	learn: 1.6519375	total: 326ms	remaining: 664ms
329:	learn: 1.6452295	total: 326ms	remaining: 662ms
330:	learn: 1.6448294	total: 327ms	remaining: 661ms
331:	learn: 1.6404292	total: 328ms	remaining: 659ms
332:	learn: 1.6341392	total: 328ms	remaining: 658ms
333:	learn: 1.6306461	total: 329ms	remaining: 656ms
334:	learn: 1.6226512	total: 330ms	remaining: 655ms
335:	learn: 1.6188058	total: 330ms	remaining: 653ms
336:	learn: 1.6140955	total: 331ms	remaining: 651ms
337:	learn: 1.6086288	total: 332ms	remaining: 650ms
338:	learn: 1.6081069	total: 333ms	remaining: 648ms
339:	learn: 1.6057617	total: 333ms	remaining: 647ms
340:	learn: 1.6039055	total: 334ms	remaining: 645ms
341:	learn: 1.5981559	total: 335ms	remaining: 644ms
342:	learn: 1.5958934	total: 335ms	remaining: 642ms
343:	learn: 1.5911641	total: 336ms	remaining: 641ms
344:	learn: 1.5847110	total: 337ms	remaining: 639ms
345:	learn: 1.5817645	total: 337ms	remaining: 638ms
346:	learn: 1.5813805	total: 338ms	remaining: 636ms
347:	learn: 1.5772484	total: 339ms	remaining: 635ms
348:	learn: 1.5737496	total: 339ms	remaining: 633ms
349:	learn: 1.5694562	total: 340ms	remaining: 632ms
350:	learn: 1.5657688	total: 341ms	remaining: 630ms
351:	learn: 1.5635290	total: 341ms	remaining: 629ms
352:	learn: 1.5604452	total: 342ms	remaining: 627ms
353:	learn: 1.5544025	total: 343ms	remaining: 626ms
354:	learn: 1.5506531	total: 344ms	remaining: 624ms
355:	learn: 1.5502778	total: 344ms	remaining: 623ms
356:	learn: 1.5460259	total: 345ms	remaining: 622ms
357:	learn: 1.5412504	total: 346ms	remaining: 620ms
358:	learn: 1.5353876	total: 347ms	remaining: 619ms
359:	learn: 1.5326947	total: 347ms	remaining: 617ms
360:	learn: 1.5297791	total: 348ms	remaining: 616ms
361:	learn: 1.5294330	total: 349ms	remaining: 615ms
362:	learn: 1.5223427	total: 349ms	remaining: 613ms
363:	learn: 1.5173549	total: 350ms	remaining: 612ms
364:	learn: 1.5124302	total: 351ms	remaining: 610ms
365:	learn: 1.5085606	total: 352ms	remaining: 609ms
366:	learn: 1.5057070	total: 352ms	remaining: 608ms
367:	learn: 1.5037624	total: 353ms	remaining: 606ms
368:	learn: 1.4982546	total: 354ms	remaining: 605ms
369:	learn: 1.4978333	total: 354ms	remaining: 603ms
370:	learn: 1.4974911	total: 355ms	remaining: 602ms
371:	learn: 1.4971589	total: 356ms	remaining: 601ms
372:	learn: 1.4968207	total: 356ms	remaining: 599ms
373:	learn: 1.4963749	total: 358ms	remaining: 599ms
374:	learn: 1.4919686	total: 359ms	remaining: 598ms
375:	learn: 1.4899279	total: 359ms	remaining: 596ms
376:	learn: 1.4869512	total: 360ms	remaining: 595ms
377:	learn: 1.4839517	total: 361ms	remaining: 593ms
378:	learn: 1.4786367	total: 361ms	remaining: 592ms
379:	learn: 1.4752274	total: 362ms	remaining: 591ms
380:	learn: 1.4716845	total: 363ms	remaining: 589ms
381:	learn: 1.4649012	total: 364ms	remaining: 588ms
382:	learn: 1.4608433	total: 364ms	remaining: 587ms
383:	learn: 1.4544622	total: 365ms	remaining: 586ms
384:	learn: 1.4508387	total: 366ms	remaining: 584ms
385:	learn: 1.4476226	total: 366ms	remaining: 583ms

In [21]:
model5 = LGBMRegressor()
model5.fit(X_train,y_train)
y_pred5 = model5.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred5))
print("MAE:",mean_absolute_error(y_test,y_pred5))
print('r2_score:',r2_score(y_test,y_pred5))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000553 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 137
[LightGBM] [Info] Number of data points in the train set: 316, number of used features: 37
[LightGBM] [Info] Start training from score 10.325949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
MSE: 16.24583760522627
MAE: 3.285241499246984
r2_score: 0.20771518383539245

In [23]:
from sklearn.ensemble import RandomForestRegressor
model6 = RandomForestRegressor(n_estimators=200,max_depth=10,random_state=42)
model6.fit(X_train,y_train)
y_pred6 = model6.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred6))
print("MAE:",mean_absolute_error(y_test,y_pred6))
print('r2_score:',r2_score(y_test,y_pred6))

MSE: 14.927958926631566
MAE: 3.0796105779468017
r2_score: 0.27198612461235583

In [28]:
from sklearn.tree import DecisionTreeRegressor
model7=DecisionTreeRegressor(random_state=42,max_depth=6)
model7.fit(X_train,y_train)
y_pred7 = model7.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred7))
print("MAE:",mean_absolute_error(y_test,y_pred7))
print('r2_score:',r2_score(y_test,y_pred7))

MSE: 18.79657924015597
MAE: 3.2961656422480994
r2_score: 0.08331938988361975