In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [2]:
df = pd.read_csv("winequality-red.csv")

In [3]:
df.shape

(1599, 12)

In [4]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [8]:
X = df.drop('quality',axis=1)
y = df['quality']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
model1 = AdaBoostRegressor(n_estimators=100,random_state=42)
model1.fit(X_train,y_train)
y_pred1 =model1.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred1))
print("MAE:",mean_absolute_error(y_test,y_pred1))
print("r2_score:",r2_score(y_test,y_pred1))

MSE: 0.37137065375810796
MAE: 0.500590654295283
r2_score: 0.4317255944525433

In [13]:
model2 = GradientBoostingRegressor()
model2.fit(X_train,y_train)
y_pred2 =model2.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred2))
print("MAE:",mean_absolute_error(y_test,y_pred2))
print("r2_score:",r2_score(y_test,y_pred2))

MSE: 0.36238906607687527
MAE: 0.48535532956396
r2_score: 0.4454692932310401

In [14]:
model3 = LGBMRegressor()
model3.fit(X_train,y_train)
y_pred3 =model3.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred3))
print("MAE:",mean_absolute_error(y_test,y_pred3))
print("r2_score:",r2_score(y_test,y_pred3))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000220 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1019
[LightGBM] [Info] Number of data points in the train set: 1279, number of used features: 11
[LightGBM] [Info] Start training from score 5.623925
MSE: 0.310977862590854
MAE: 0.42424193636061674
r2_score: 0.5241391364290642

In [15]:
model4 = XGBRegressor()
model4.fit(X_train,y_train)
y_pred4 =model4.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred4))
print("MAE:",mean_absolute_error(y_test,y_pred4))
print("r2_score:",r2_score(y_test,y_pred4))

MSE: 0.35126441717147827
MAE: 0.4175254702568054
r2_score: 0.4624922275543213

In [16]:
model5 = CatBoostRegressor()
model5.fit(X_train,y_train)
y_pred5 =model5.predict(X_test)
print("MSE:",mean_squared_error(y_test,y_pred5))
print("MAE:",mean_absolute_error(y_test,y_pred5))
print("r2_score:",r2_score(y_test,y_pred5))

Learning rate set to 0.042566
0:	learn: 0.7961722	total: 58.9ms	remaining: 58.9s
1:	learn: 0.7858269	total: 61.4ms	remaining: 30.6s
2:	learn: 0.7768657	total: 63.4ms	remaining: 21.1s
3:	learn: 0.7683315	total: 65.1ms	remaining: 16.2s
4:	learn: 0.7595828	total: 66.3ms	remaining: 13.2s
5:	learn: 0.7519151	total: 67.6ms	remaining: 11.2s
6:	learn: 0.7438187	total: 68.8ms	remaining: 9.76s
7:	learn: 0.7359962	total: 69.9ms	remaining: 8.66s
8:	learn: 0.7295845	total: 70.9ms	remaining: 7.81s
9:	learn: 0.7242132	total: 71.8ms	remaining: 7.11s
10:	learn: 0.7183437	total: 72.8ms	remaining: 6.55s
11:	learn: 0.7121187	total: 74.1ms	remaining: 6.1s
12:	learn: 0.7060758	total: 75ms	remaining: 5.69s
13:	learn: 0.7003074	total: 75.8ms	remaining: 5.34s
14:	learn: 0.6943954	total: 76.6ms	remaining: 5.03s
15:	learn: 0.6895442	total: 77.4ms	remaining: 4.76s
16:	learn: 0.6854317	total: 78.3ms	remaining: 4.53s
17:	learn: 0.6812536	total: 79.1ms	remaining: 4.32s
18:	learn: 0.6763736	total: 80ms	remaining: 4.13s
19:	learn: 0.6717135	total: 80.7ms	remaining: 3.95s
20:	learn: 0.6680444	total: 81.4ms	remaining: 3.8s
21:	learn: 0.6645304	total: 82.1ms	remaining: 3.65s
22:	learn: 0.6609764	total: 82.9ms	remaining: 3.52s
23:	learn: 0.6580992	total: 84ms	remaining: 3.42s
24:	learn: 0.6545500	total: 84.9ms	remaining: 3.31s
25:	learn: 0.6518601	total: 86.4ms	remaining: 3.24s
26:	learn: 0.6490535	total: 87.2ms	remaining: 3.14s
27:	learn: 0.6455399	total: 88ms	remaining: 3.05s
28:	learn: 0.6429600	total: 89ms	remaining: 2.98s
29:	learn: 0.6401382	total: 89.7ms	remaining: 2.9s
30:	learn: 0.6378209	total: 90.5ms	remaining: 2.83s
31:	learn: 0.6352484	total: 91.3ms	remaining: 2.76s
32:	learn: 0.6329512	total: 92.2ms	remaining: 2.7s
33:	learn: 0.6305037	total: 92.9ms	remaining: 2.64s
34:	learn: 0.6286633	total: 93.6ms	remaining: 2.58s
35:	learn: 0.6268408	total: 94.3ms	remaining: 2.53s
36:	learn: 0.6249086	total: 95ms	remaining: 2.47s
37:	learn: 0.6225065	total: 95.8ms	remaining: 2.42s
38:	learn: 0.6204105	total: 96.5ms	remaining: 2.38s
39:	learn: 0.6180567	total: 97.2ms	remaining: 2.33s
40:	learn: 0.6161674	total: 97.9ms	remaining: 2.29s
41:	learn: 0.6147920	total: 98.6ms	remaining: 2.25s
42:	learn: 0.6122723	total: 99.3ms	remaining: 2.21s
43:	learn: 0.6106512	total: 100ms	remaining: 2.17s
44:	learn: 0.6093130	total: 101ms	remaining: 2.13s
45:	learn: 0.6080023	total: 101ms	remaining: 2.1s
46:	learn: 0.6061164	total: 102ms	remaining: 2.06s
47:	learn: 0.6046947	total: 102ms	remaining: 2.03s
48:	learn: 0.6035136	total: 103ms	remaining: 2s
49:	learn: 0.6016529	total: 104ms	remaining: 1.97s
50:	learn: 0.5999510	total: 105ms	remaining: 1.94s
51:	learn: 0.5986229	total: 105ms	remaining: 1.92s
52:	learn: 0.5975244	total: 106ms	remaining: 1.89s
53:	learn: 0.5958230	total: 106ms	remaining: 1.86s
54:	learn: 0.5948186	total: 107ms	remaining: 1.84s
55:	learn: 0.5932799	total: 108ms	remaining: 1.81s
56:	learn: 0.5921101	total: 108ms	remaining: 1.79s
57:	learn: 0.5906616	total: 109ms	remaining: 1.76s
58:	learn: 0.5894809	total: 109ms	remaining: 1.74s
59:	learn: 0.5887277	total: 111ms	remaining: 1.73s
60:	learn: 0.5874725	total: 111ms	remaining: 1.71s
61:	learn: 0.5866278	total: 112ms	remaining: 1.69s
62:	learn: 0.5857844	total: 113ms	remaining: 1.67s
63:	learn: 0.5850586	total: 113ms	remaining: 1.66s
64:	learn: 0.5839590	total: 114ms	remaining: 1.64s
65:	learn: 0.5825903	total: 114ms	remaining: 1.62s
66:	learn: 0.5817478	total: 115ms	remaining: 1.6s
67:	learn: 0.5807341	total: 115ms	remaining: 1.58s
68:	learn: 0.5798676	total: 116ms	remaining: 1.56s
69:	learn: 0.5787462	total: 117ms	remaining: 1.55s
70:	learn: 0.5772231	total: 117ms	remaining: 1.53s
71:	learn: 0.5763525	total: 118ms	remaining: 1.51s
72:	learn: 0.5756788	total: 118ms	remaining: 1.5s
73:	learn: 0.5753313	total: 119ms	remaining: 1.48s
74:	learn: 0.5742544	total: 119ms	remaining: 1.47s
75:	learn: 0.5736691	total: 120ms	remaining: 1.46s
76:	learn: 0.5727423	total: 121ms	remaining: 1.45s
77:	learn: 0.5720600	total: 121ms	remaining: 1.43s
78:	learn: 0.5717010	total: 122ms	remaining: 1.42s
79:	learn: 0.5706643	total: 122ms	remaining: 1.41s
80:	learn: 0.5699925	total: 123ms	remaining: 1.4s
81:	learn: 0.5692144	total: 123ms	remaining: 1.38s
82:	learn: 0.5684216	total: 124ms	remaining: 1.37s
83:	learn: 0.5680464	total: 125ms	remaining: 1.36s
84:	learn: 0.5673461	total: 125ms	remaining: 1.35s
85:	learn: 0.5659301	total: 126ms	remaining: 1.33s
86:	learn: 0.5655778	total: 126ms	remaining: 1.32s
87:	learn: 0.5651495	total: 127ms	remaining: 1.31s
88:	learn: 0.5645175	total: 127ms	remaining: 1.3s
89:	learn: 0.5640838	total: 127ms	remaining: 1.29s
90:	learn: 0.5631532	total: 128ms	remaining: 1.28s
91:	learn: 0.5622997	total: 128ms	remaining: 1.27s
92:	learn: 0.5610738	total: 129ms	remaining: 1.26s
93:	learn: 0.5602448	total: 130ms	remaining: 1.25s
94:	learn: 0.5592176	total: 130ms	remaining: 1.24s
95:	learn: 0.5589039	total: 130ms	remaining: 1.23s
96:	learn: 0.5584382	total: 131ms	remaining: 1.22s
97:	learn: 0.5577144	total: 131ms	remaining: 1.21s
98:	learn: 0.5575335	total: 132ms	remaining: 1.2s
99:	learn: 0.5570035	total: 132ms	remaining: 1.19s
100:	learn: 0.5564891	total: 133ms	remaining: 1.18s
101:	learn: 0.5557460	total: 133ms	remaining: 1.17s
102:	learn: 0.5550914	total: 134ms	remaining: 1.16s
103:	learn: 0.5543829	total: 134ms	remaining: 1.16s
104:	learn: 0.5540359	total: 135ms	remaining: 1.15s
105:	learn: 0.5533114	total: 135ms	remaining: 1.14s
106:	learn: 0.5527796	total: 135ms	remaining: 1.13s
107:	learn: 0.5518477	total: 136ms	remaining: 1.12s
108:	learn: 0.5512850	total: 136ms	remaining: 1.11s
109:	learn: 0.5508803	total: 137ms	remaining: 1.11s
110:	learn: 0.5504530	total: 137ms	remaining: 1.1s
111:	learn: 0.5500112	total: 138ms	remaining: 1.09s
112:	learn: 0.5494377	total: 138ms	remaining: 1.08s
113:	learn: 0.5492567	total: 138ms	remaining: 1.07s
114:	learn: 0.5489120	total: 139ms	remaining: 1.07s
115:	learn: 0.5484560	total: 139ms	remaining: 1.06s
116:	learn: 0.5474261	total: 140ms	remaining: 1.05s
117:	learn: 0.5473154	total: 140ms	remaining: 1.05s
118:	learn: 0.5470912	total: 141ms	remaining: 1.04s
119:	learn: 0.5465202	total: 141ms	remaining: 1.03s
120:	learn: 0.5455716	total: 141ms	remaining: 1.03s
121:	learn: 0.5445341	total: 142ms	remaining: 1.02s
122:	learn: 0.5442071	total: 142ms	remaining: 1.01s
123:	learn: 0.5433285	total: 143ms	remaining: 1.01s
124:	learn: 0.5421256	total: 143ms	remaining: 1s
125:	learn: 0.5416539	total: 143ms	remaining: 994ms
126:	learn: 0.5415159	total: 144ms	remaining: 988ms
127:	learn: 0.5413950	total: 144ms	remaining: 982ms
128:	learn: 0.5408613	total: 145ms	remaining: 977ms
129:	learn: 0.5399355	total: 145ms	remaining: 970ms
130:	learn: 0.5390062	total: 145ms	remaining: 965ms
131:	learn: 0.5383565	total: 146ms	remaining: 959ms
132:	learn: 0.5374236	total: 146ms	remaining: 953ms
133:	learn: 0.5369460	total: 147ms	remaining: 947ms
134:	learn: 0.5365239	total: 147ms	remaining: 941ms
135:	learn: 0.5360727	total: 147ms	remaining: 936ms
136:	learn: 0.5352155	total: 148ms	remaining: 930ms
137:	learn: 0.5345856	total: 148ms	remaining: 925ms
138:	learn: 0.5343230	total: 148ms	remaining: 920ms
139:	learn: 0.5337378	total: 149ms	remaining: 914ms
140:	learn: 0.5334565	total: 149ms	remaining: 910ms
141:	learn: 0.5333452	total: 150ms	remaining: 904ms
142:	learn: 0.5331521	total: 150ms	remaining: 900ms
143:	learn: 0.5329264	total: 151ms	remaining: 895ms
144:	learn: 0.5323540	total: 151ms	remaining: 890ms
145:	learn: 0.5318809	total: 151ms	remaining: 885ms
146:	learn: 0.5315372	total: 152ms	remaining: 880ms
147:	learn: 0.5310328	total: 152ms	remaining: 876ms
148:	learn: 0.5303475	total: 153ms	remaining: 872ms
149:	learn: 0.5300092	total: 153ms	remaining: 867ms
150:	learn: 0.5292796	total: 153ms	remaining: 863ms
151:	learn: 0.5286488	total: 154ms	remaining: 858ms
152:	learn: 0.5283714	total: 154ms	remaining: 854ms
153:	learn: 0.5279718	total: 155ms	remaining: 850ms
154:	learn: 0.5271867	total: 155ms	remaining: 845ms
155:	learn: 0.5270964	total: 155ms	remaining: 841ms
156:	learn: 0.5268125	total: 156ms	remaining: 836ms
157:	learn: 0.5267160	total: 156ms	remaining: 832ms
158:	learn: 0.5266181	total: 157ms	remaining: 828ms
159:	learn: 0.5257908	total: 157ms	remaining: 824ms
160:	learn: 0.5250501	total: 157ms	remaining: 820ms
161:	learn: 0.5248933	total: 158ms	remaining: 817ms
162:	learn: 0.5247124	total: 158ms	remaining: 813ms
163:	learn: 0.5245881	total: 159ms	remaining: 809ms
164:	learn: 0.5244850	total: 159ms	remaining: 805ms
165:	learn: 0.5241111	total: 160ms	remaining: 802ms
166:	learn: 0.5234759	total: 160ms	remaining: 798ms
167:	learn: 0.5233798	total: 161ms	remaining: 795ms
168:	learn: 0.5229926	total: 161ms	remaining: 792ms
169:	learn: 0.5228364	total: 162ms	remaining: 789ms
170:	learn: 0.5220069	total: 162ms	remaining: 785ms
171:	learn: 0.5218428	total: 162ms	remaining: 781ms
172:	learn: 0.5213013	total: 163ms	remaining: 778ms
173:	learn: 0.5210349	total: 163ms	remaining: 774ms
174:	learn: 0.5209592	total: 163ms	remaining: 771ms
175:	learn: 0.5208315	total: 164ms	remaining: 767ms
176:	learn: 0.5204854	total: 164ms	remaining: 764ms
177:	learn: 0.5200265	total: 165ms	remaining: 760ms
178:	learn: 0.5195712	total: 165ms	remaining: 757ms
179:	learn: 0.5194275	total: 166ms	remaining: 754ms
180:	learn: 0.5192560	total: 166ms	remaining: 751ms
181:	learn: 0.5184801	total: 166ms	remaining: 748ms
182:	learn: 0.5177251	total: 167ms	remaining: 745ms
183:	learn: 0.5168956	total: 167ms	remaining: 742ms
184:	learn: 0.5167879	total: 168ms	remaining: 739ms
185:	learn: 0.5164904	total: 168ms	remaining: 736ms
186:	learn: 0.5164242	total: 168ms	remaining: 733ms
187:	learn: 0.5163080	total: 169ms	remaining: 730ms
188:	learn: 0.5157326	total: 169ms	remaining: 727ms
189:	learn: 0.5156605	total: 170ms	remaining: 724ms
190:	learn: 0.5155819	total: 170ms	remaining: 721ms
191:	learn: 0.5149095	total: 170ms	remaining: 717ms
192:	learn: 0.5146069	total: 171ms	remaining: 715ms
193:	learn: 0.5145371	total: 171ms	remaining: 711ms
194:	learn: 0.5144511	total: 172ms	remaining: 709ms
195:	learn: 0.5140138	total: 172ms	remaining: 706ms
196:	learn: 0.5136046	total: 172ms	remaining: 703ms
197:	learn: 0.5135227	total: 173ms	remaining: 700ms
198:	learn: 0.5124546	total: 173ms	remaining: 697ms
199:	learn: 0.5122605	total: 174ms	remaining: 694ms
200:	learn: 0.5121360	total: 174ms	remaining: 691ms
201:	learn: 0.5120498	total: 174ms	remaining: 688ms
202:	learn: 0.5119623	total: 175ms	remaining: 686ms
203:	learn: 0.5118195	total: 175ms	remaining: 683ms
204:	learn: 0.5117441	total: 176ms	remaining: 681ms
205:	learn: 0.5116389	total: 176ms	remaining: 678ms
206:	learn: 0.5114102	total: 176ms	remaining: 676ms
207:	learn: 0.5102262	total: 177ms	remaining: 673ms
208:	learn: 0.5101164	total: 177ms	remaining: 670ms
209:	learn: 0.5100202	total: 178ms	remaining: 668ms
210:	learn: 0.5098521	total: 178ms	remaining: 665ms
211:	learn: 0.5090215	total: 178ms	remaining: 663ms
212:	learn: 0.5089530	total: 179ms	remaining: 661ms
213:	learn: 0.5082010	total: 179ms	remaining: 658ms
214:	learn: 0.5081343	total: 180ms	remaining: 656ms
215:	learn: 0.5071640	total: 180ms	remaining: 654ms
216:	learn: 0.5070621	total: 181ms	remaining: 652ms
217:	learn: 0.5069333	total: 181ms	remaining: 650ms
218:	learn: 0.5068501	total: 182ms	remaining: 647ms
219:	learn: 0.5059661	total: 182ms	remaining: 645ms
220:	learn: 0.5059018	total: 182ms	remaining: 643ms
221:	learn: 0.5049489	total: 183ms	remaining: 641ms
222:	learn: 0.5048713	total: 183ms	remaining: 639ms
223:	learn: 0.5047639	total: 184ms	remaining: 637ms
224:	learn: 0.5037481	total: 184ms	remaining: 634ms
225:	learn: 0.5030812	total: 185ms	remaining: 632ms
226:	learn: 0.5020331	total: 185ms	remaining: 630ms
227:	learn: 0.5019585	total: 185ms	remaining: 628ms
228:	learn: 0.5015141	total: 186ms	remaining: 625ms
229:	learn: 0.5014158	total: 186ms	remaining: 623ms
230:	learn: 0.5013421	total: 186ms	remaining: 621ms
231:	learn: 0.5012618	total: 187ms	remaining: 618ms
232:	learn: 0.5004287	total: 187ms	remaining: 616ms
233:	learn: 0.4996049	total: 188ms	remaining: 615ms
234:	learn: 0.4987809	total: 189ms	remaining: 614ms
235:	learn: 0.4980861	total: 189ms	remaining: 612ms
236:	learn: 0.4976563	total: 189ms	remaining: 609ms
237:	learn: 0.4971198	total: 190ms	remaining: 607ms
238:	learn: 0.4963503	total: 190ms	remaining: 605ms
239:	learn: 0.4953480	total: 190ms	remaining: 603ms
240:	learn: 0.4952948	total: 191ms	remaining: 601ms
241:	learn: 0.4944087	total: 191ms	remaining: 599ms
242:	learn: 0.4943200	total: 192ms	remaining: 597ms
243:	learn: 0.4936100	total: 192ms	remaining: 595ms
244:	learn: 0.4930115	total: 192ms	remaining: 593ms
245:	learn: 0.4923764	total: 193ms	remaining: 591ms
246:	learn: 0.4917474	total: 193ms	remaining: 589ms
247:	learn: 0.4909337	total: 193ms	remaining: 587ms
248:	learn: 0.4906603	total: 194ms	remaining: 585ms
249:	learn: 0.4905879	total: 194ms	remaining: 583ms
250:	learn: 0.4905393	total: 196ms	remaining: 584ms
251:	learn: 0.4904587	total: 196ms	remaining: 582ms
252:	learn: 0.4903972	total: 197ms	remaining: 580ms
253:	learn: 0.4899720	total: 197ms	remaining: 578ms
254:	learn: 0.4898947	total: 197ms	remaining: 576ms
255:	learn: 0.4892648	total: 198ms	remaining: 575ms
256:	learn: 0.4883558	total: 198ms	remaining: 573ms
257:	learn: 0.4875992	total: 198ms	remaining: 571ms
258:	learn: 0.4864219	total: 199ms	remaining: 569ms
259:	learn: 0.4863582	total: 199ms	remaining: 568ms
260:	learn: 0.4857429	total: 200ms	remaining: 566ms
261:	learn: 0.4856831	total: 200ms	remaining: 564ms
262:	learn: 0.4850460	total: 201ms	remaining: 562ms
263:	learn: 0.4844368	total: 201ms	remaining: 561ms
264:	learn: 0.4835754	total: 201ms	remaining: 559ms
265:	learn: 0.4830121	total: 202ms	remaining: 557ms
266:	learn: 0.4825692	total: 202ms	remaining: 555ms
267:	learn: 0.4825264	total: 203ms	remaining: 554ms
268:	learn: 0.4816897	total: 203ms	remaining: 552ms
269:	learn: 0.4811022	total: 204ms	remaining: 550ms
270:	learn: 0.4800727	total: 204ms	remaining: 549ms
271:	learn: 0.4797784	total: 204ms	remaining: 547ms
272:	learn: 0.4793531	total: 205ms	remaining: 545ms
273:	learn: 0.4784421	total: 205ms	remaining: 544ms
274:	learn: 0.4784012	total: 206ms	remaining: 542ms
275:	learn: 0.4777320	total: 206ms	remaining: 540ms
276:	learn: 0.4776583	total: 206ms	remaining: 538ms
277:	learn: 0.4768916	total: 207ms	remaining: 537ms
278:	learn: 0.4763012	total: 207ms	remaining: 535ms
279:	learn: 0.4755401	total: 207ms	remaining: 533ms
280:	learn: 0.4747897	total: 208ms	remaining: 532ms
281:	learn: 0.4741234	total: 208ms	remaining: 530ms
282:	learn: 0.4733520	total: 209ms	remaining: 529ms
283:	learn: 0.4724732	total: 209ms	remaining: 528ms
284:	learn: 0.4719580	total: 210ms	remaining: 527ms
285:	learn: 0.4712699	total: 210ms	remaining: 525ms
286:	learn: 0.4710007	total: 211ms	remaining: 524ms
287:	learn: 0.4709468	total: 211ms	remaining: 523ms
288:	learn: 0.4706049	total: 212ms	remaining: 522ms
289:	learn: 0.4705657	total: 213ms	remaining: 521ms
290:	learn: 0.4698915	total: 213ms	remaining: 519ms
291:	learn: 0.4691914	total: 214ms	remaining: 518ms
292:	learn: 0.4685175	total: 214ms	remaining: 517ms
293:	learn: 0.4674246	total: 215ms	remaining: 516ms
294:	learn: 0.4673402	total: 215ms	remaining: 514ms
295:	learn: 0.4671491	total: 216ms	remaining: 513ms
296:	learn: 0.4663808	total: 216ms	remaining: 511ms
297:	learn: 0.4657630	total: 216ms	remaining: 510ms
298:	learn: 0.4651730	total: 217ms	remaining: 508ms
299:	learn: 0.4648563	total: 217ms	remaining: 507ms
300:	learn: 0.4636036	total: 218ms	remaining: 506ms
301:	learn: 0.4635605	total: 218ms	remaining: 504ms
302:	learn: 0.4634858	total: 219ms	remaining: 503ms
303:	learn: 0.4629362	total: 219ms	remaining: 501ms
304:	learn: 0.4628220	total: 219ms	remaining: 500ms
305:	learn: 0.4627332	total: 220ms	remaining: 498ms
306:	learn: 0.4622953	total: 220ms	remaining: 497ms
307:	learn: 0.4617264	total: 220ms	remaining: 495ms
308:	learn: 0.4610746	total: 221ms	remaining: 494ms
309:	learn: 0.4602899	total: 221ms	remaining: 493ms
310:	learn: 0.4594877	total: 222ms	remaining: 491ms
311:	learn: 0.4591717	total: 222ms	remaining: 490ms
312:	learn: 0.4591059	total: 223ms	remaining: 489ms
313:	learn: 0.4584557	total: 223ms	remaining: 488ms
314:	learn: 0.4584156	total: 224ms	remaining: 487ms
315:	learn: 0.4583495	total: 224ms	remaining: 485ms
316:	learn: 0.4575652	total: 225ms	remaining: 484ms
317:	learn: 0.4569929	total: 225ms	remaining: 483ms
318:	learn: 0.4566241	total: 225ms	remaining: 481ms
319:	learn: 0.4561182	total: 226ms	remaining: 480ms
320:	learn: 0.4558753	total: 226ms	remaining: 479ms
321:	learn: 0.4550667	total: 227ms	remaining: 477ms
322:	learn: 0.4542368	total: 227ms	remaining: 476ms
323:	learn: 0.4536007	total: 227ms	remaining: 475ms
324:	learn: 0.4535471	total: 229ms	remaining: 475ms
325:	learn: 0.4535083	total: 229ms	remaining: 473ms
326:	learn: 0.4528961	total: 229ms	remaining: 472ms
327:	learn: 0.4524668	total: 230ms	remaining: 471ms
328:	learn: 0.4524270	total: 230ms	remaining: 469ms
329:	learn: 0.4518333	total: 231ms	remaining: 468ms
330:	learn: 0.4516035	total: 231ms	remaining: 467ms
331:	learn: 0.4504295	total: 232ms	remaining: 466ms
332:	learn: 0.4503687	total: 232ms	remaining: 465ms
333:	learn: 0.4499558	total: 232ms	remaining: 463ms
334:	learn: 0.4499173	total: 233ms	remaining: 462ms
335:	learn: 0.4491344	total: 233ms	remaining: 461ms
336:	learn: 0.4487146	total: 233ms	remaining: 459ms
337:	learn: 0.4477619	total: 234ms	remaining: 458ms
338:	learn: 0.4474432	total: 234ms	remaining: 457ms
339:	learn: 0.4465963	total: 235ms	remaining: 456ms
340:	learn: 0.4458801	total: 235ms	remaining: 454ms
341:	learn: 0.4455701	total: 236ms	remaining: 453ms
342:	learn: 0.4448141	total: 236ms	remaining: 452ms
343:	learn: 0.4439901	total: 236ms	remaining: 451ms
344:	learn: 0.4433215	total: 237ms	remaining: 450ms
345:	learn: 0.4429711	total: 237ms	remaining: 448ms
346:	learn: 0.4426060	total: 238ms	remaining: 447ms
347:	learn: 0.4422948	total: 238ms	remaining: 446ms
348:	learn: 0.4418011	total: 238ms	remaining: 445ms
349:	learn: 0.4414221	total: 239ms	remaining: 444ms
350:	learn: 0.4413902	total: 239ms	remaining: 442ms
351:	learn: 0.4413614	total: 240ms	remaining: 441ms
352:	learn: 0.4411125	total: 240ms	remaining: 440ms
353:	learn: 0.4410500	total: 240ms	remaining: 439ms
354:	learn: 0.4406704	total: 241ms	remaining: 437ms
355:	learn: 0.4402368	total: 241ms	remaining: 436ms
356:	learn: 0.4396856	total: 241ms	remaining: 435ms
357:	learn: 0.4390577	total: 242ms	remaining: 434ms
358:	learn: 0.4387705	total: 242ms	remaining: 433ms
359:	learn: 0.4382836	total: 243ms	remaining: 432ms
360:	learn: 0.4378231	total: 243ms	remaining: 430ms
361:	learn: 0.4368835	total: 244ms	remaining: 429ms
362:	learn: 0.4364736	total: 244ms	remaining: 428ms
363:	learn: 0.4360644	total: 244ms	remaining: 427ms
364:	learn: 0.4357652	total: 245ms	remaining: 426ms
365:	learn: 0.4357365	total: 245ms	remaining: 425ms
366:	learn: 0.4357084	total: 246ms	remaining: 424ms
367:	learn: 0.4349906	total: 246ms	remaining: 422ms
368:	learn: 0.4343490	total: 246ms	remaining: 421ms
369:	learn: 0.4339228	total: 247ms	remaining: 420ms
370:	learn: 0.4335690	total: 247ms	remaining: 419ms
371:	learn: 0.4330691	total: 248ms	remaining: 418ms
372:	learn: 0.4321800	total: 248ms	remaining: 417ms
373:	learn: 0.4316399	total: 249ms	remaining: 416ms
374:	learn: 0.4311424	total: 249ms	remaining: 415ms
375:	learn: 0.4307778	total: 250ms	remaining: 414ms
376:	learn: 0.4306963	total: 250ms	remaining: 413ms
377:	learn: 0.4299240	total: 250ms	remaining: 412ms
378:	learn: 0.4290446	total: 251ms	remaining: 411ms
379:	learn: 0.4285245	total: 251ms	remaining: 410ms
380:	learn: 0.4284964	total: 252ms	remaining: 409ms
381:	learn: 0.4278766	total: 252ms	remaining: 408ms
382:	learn: 0.4273502	total: 252ms	remaining: 407ms
383:	learn: 0.4270958	total: 253ms	remaining: 406ms
384:	learn: 0.4265929	total: 253ms	remaining: 404ms